(function() {var c=void 0,f=!0,h=null,j=!1;function l(a){return function(){return this[a]}}function m(a){return function(){return a}}var n,aa=this;aa.bc=f;function s(a,b){var d=a.split("."),e=aa;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&b!==c?e[g]=b:e=e[g]?e[g]:e[g]={}}function t(a,b){function d(){}d.prototype=b.prototype;a.i=b.prototype;a.prototype=new d;a.prototype.constructor=a};document.createElement("video");document.createElement("audio");function u(a,b,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(u.Q[a])return u.Q[a];a=u.g(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new v(a,b,d)}var x=u;u.Ta="GENERATED_CDN_VSN";u.Sa="https:"==document.location.protocol?"https://":"http://";
u.options={techOrder:["html5","flash"],html5:{},flash:{tc:u.Sa+"vjs.zencdn.net/c/video-js.swf"},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}}};u.Q={};"GENERATED_CDN_VSN"!=u.Ta&&(x.options.flash.swf=u.Sa+"vjs.zencdn.net/"+u.Ta+"/video-js.swf");u.jc={};u.e=function(a,b,d){var e=u.getData(a);e.r||(e.r={});e.r[b]||(e.r[b]=[]);d.q||(d.q=u.q++);e.r[b].push(d);e.K||(e.disabled=j,e.K=function(b){if(!e.disabled){b=u.Za(b);var d=e.r[b.type];if(d)for(var d=d.slice(0),k=0,r=d.length;k<r&&!b.eb();k++)d[k].call(a,b)}});1==e.r[b].length&&(document.addEventListener?a.addEventListener(b,e.K,j):document.attachEvent&&a.attachEvent("on"+b,e.K))};
u.k=function(a,b,d){if(u.cb(a)){var e=u.getData(a);if(e.r)if(b){var g=e.r[b];if(g){if(d){if(d.q)for(e=0;e<g.length;e++)g[e].q===d.q&&g.splice(e--,1)}else e.r[b]=[];u.Wa(a,b)}}else for(g in e.r)b=g,e.r[b]=[],u.Wa(a,b)}};u.Wa=function(a,b){var d=u.getData(a);0===d.r[b].length&&(delete d.r[b],document.removeEventListener?a.removeEventListener(b,d.K,j):document.detachEvent&&a.detachEvent("on"+b,d.K));u.ma(d.r)&&(delete d.r,delete d.K,delete d.disabled);u.ma(d)&&u.Pa(a)};
u.Za=function(a){function b(){return f}function d(){return j}if(!a||!a.Fa){var e=a||window.event,g;for(g in e)a[g]=e[g];a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){a.returnValue=j;a.la=b};a.la=d;a.stopPropagation=function(){a.cancelBubble=f;a.Fa=b};a.Fa=d;a.stopImmediatePropagation=function(){a.eb=b;a.stopPropagation()};a.eb=d;a.clientX!=h&&(e=document.documentElement,g=document.body,a.pageX=a.clientX+(e&&
e.scrollLeft||g&&g.scrollLeft||0)-(e&&e.clientLeft||g&&g.clientLeft||0),a.pageY=a.clientY+(e&&e.scrollTop||g&&g.scrollTop||0)-(e&&e.clientTop||g&&g.clientTop||0));a.which=a.charCode||a.keyCode;a.button!=h&&(a.button=a.button&1?0:a.button&4?1:a.button&2?2:0)}return a};
u.h=function(a,b){var d=u.cb(a)?u.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof b&&(b={type:b,target:a});b=u.Za(b);d.K&&d.K.call(a,b);if(e&&!b.Fa())u.h(e,b);else if(!e&&!b.la()&&(d=u.getData(b.target),b.target[b.type])){d.disabled=f;if("function"===typeof b.target[b.type])b.target[b.type]();d.disabled=j}return!b.la()};u.A=function(a,b,d){u.e(a,b,function(){u.k(a,b,arguments.callee);d.apply(this,arguments)})};u.ic={};u.d=function(a,b){var d=document.createElement(a||"div"),e;for(e in b)b.hasOwnProperty(e)&&(d[e]=b[e]);return d};u.J=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};u.U=function(a,b){if(a)for(var d in a)a.hasOwnProperty(d)&&b.call(this,d,a[d])};u.t=function(a,b){if(!b)return a;for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);return a};u.bind=function(a,b,d){function e(){return b.apply(a,arguments)}b.q||(b.q=u.q++);e.q=d?d+"_"+b.q:b.q;return e};u.N={};u.q=1;u.expando="vdata"+(new Date).getTime();
u.getData=function(a){var b=a[u.expando];b||(b=a[u.expando]=u.q++,u.N[b]={});return u.N[b]};u.cb=function(a){a=a[u.expando];return!(!a||u.ma(u.N[a]))};u.Pa=function(a){var b=a[u.expando];if(b){delete u.N[b];try{delete a[u.expando]}catch(d){a.removeAttribute?a.removeAttribute(u.expando):a[u.expando]=h}}};u.ma=function(a){for(var b in a)if(a[b]!==h)return j;return f};u.n=function(a,b){-1==(" "+a.className+" ").indexOf(" "+b+" ")&&(a.className=""===a.className?b:a.className+" "+b)};
u.v=function(a,b){if(-1!=a.className.indexOf(b)){var d=a.className.split(" ");d.splice(d.indexOf(b),1);a.className=d.join(" ")}};u.tb=u.d("video");u.C=navigator.userAgent;u.rb=!!u.C.match(/iPad/i);u.qb=!!u.C.match(/iPhone/i);u.sb=!!u.C.match(/iPod/i);u.pb=u.rb||u.qb||u.sb;var ba=u,ca;var da=u.C.match(/OS (\d+)_/i);ca=da&&da[1]?da[1]:c;ba.cc=ca;u.nb=!!u.C.match(/Android.*AppleWebKit/i);var ea=u,fa=u.C.match(/Android (\d+)\./i);ea.mb=fa&&fa[1]?fa[1]:h;u.ob=function(){return!!u.C.match("Firefox")};
u.O=function(a){var b={};if(a&&a.attributes&&0<a.attributes.length)for(var d=a.attributes,e,g,p=d.length-1;0<=p;p--){e=d[p].name;g=d[p].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==h?f:j;b[e]=g}return b};
u.Ea=function(a,b){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(b):a.currentStyle&&(b=b.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),d=a.currentStyle[b]);return d};u.W=function(a,b){b.firstChild?b.insertBefore(a,b.firstChild):b.appendChild(a)};u.Qa={};u.g=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
u.p=function(a,b){b=b||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),p=Math.floor(b/60%60),k=Math.floor(b/3600),g=0<g||0<k?g+":":"";return g+(((g||10<=p)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};u.xb=function(){document.body.focus();document.onselectstart=m(j)};u.Yb=function(){document.onselectstart=m(f)};u.trim=function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")};u.round=function(a,b){b||(b=0);return Math.round(a*Math.pow(10,b))/Math.pow(10,b)};
u.Aa=function(a){return{length:1,start:m(0),end:function(){return a}}};
u.get=function(a,b,d){var e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});var g=new XMLHttpRequest;try{g.open("GET",a)}catch(p){d(p)}g.onreadystatechange=
function(){4===g.readyState&&(200===g.status||e&&0===g.status?b(g.responseText):d&&d())};try{g.send()}catch(k){d&&d(k)}};u.Tb=function(a){var b=window.localStorage||j;if(b)try{b.volume=a}catch(d){22==d.code||1014==d.code?u.log("LocalStorage Full (VideoJS)",d):u.log("LocalStorage Error (VideoJS)",d)}};u.ka=function(a){a.match(/^https?:\/\//)||(a=u.d("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
u.log=function(){u.log.history=u.log.history||[];u.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};u.Eb="getBoundingClientRect"in document.documentElement?function(a){var b;try{b=a.getBoundingClientRect()}catch(d){}if(!b)return 0;a=document.body;return b.left+(window.pageXOffset||a.scrollLeft)-(document.documentElement.clientLeft||a.clientLeft||0)}:function(a){for(var b=a.offsetLeft;a=a.offsetParent;)b+=a.offsetLeft;return b};function y(a,b,d){this.a=a;b=this.f=ga(this,this.f,b);this.L=b.id||(b.el&&b.el.id?b.el.id:a.id()+"_component_"+u.q++);this.Jb=b.name||h;this.b=b.el||this.d();this.D=[];this.ia={};this.H={};if((a=this.f)&&a.children){var e=this;u.U(a.children,function(a,b){b!==j&&!b.loadEvent&&(e[a]=e.G(a,b))})}z(this,d)}n=y.prototype;
n.m=function(){if(this.D)for(var a=this.D.length-1;0<=a;a--)this.D[a].m();this.H=this.ia=this.D=h;this.k();this.b.parentNode&&this.b.parentNode.removeChild(this.b);u.Pa(this.b);this.b=h};n.Ob=l("a");function ga(a,b,d){var e,g,p,k,r;p=Object.prototype.hasOwnProperty;g=Object.prototype.toString;b=b||{};e={};u.U(b,function(a,b){e[a]=b});if(!d)return e;for(k in d)p.call(d,k)&&(b=e[k],r=d[k],e[k]="[object Object]"===g.call(b)&&"[object Object]"===g.call(r)?ga(a,b,r):d[k]);return e}
n.d=function(a,b){return u.d(a,b)};n.g=l("b");n.id=l("L");n.name=l("Jb");n.children=l("D");n.G=function(a,b){var d,e,g;"string"===typeof a?(e=a,b=b||{},d=b.componentClass||u.J(e),b.name=e,d=new window.videojs[d](this.a||this,b)):d=a;e=d.name();g=d.id();this.D.push(d);g&&(this.ia[g]=d);e&&(this.H[e]=d);this.b.appendChild(d.g());return d};
n.removeChild=function(a){"string"===typeof a&&(a=this.H[a]);if(a&&this.D){for(var b=j,d=this.D.length-1;0<=d;d--)if(this.D[d]===a){b=f;this.D.splice(d,1);break}b&&(this.ia[a.id]=h,this.H[a.name]=h,(b=a.g())&&b.parentNode===this.b&&this.b.removeChild(a.g()))}};n.z=m("");n.e=function(a,b){u.e(this.b,a,u.bind(this,b));return this};n.k=function(a,b){u.k(this.b,a,b);return this};n.A=function(a,b){u.A(this.b,a,u.bind(this,b));return this};n.h=function(a,b){u.h(this.b,a,b);return this};
function z(a,b){b&&(a.X?b.call(a):(a.ta===c&&(a.ta=[]),a.ta.push(b)))}function A(a){a.X=f;var b=a.ta;if(b&&0<b.length){for(var d=0,e=b.length;d<e;d++)b[d].call(a);a.ta=[];a.h("ready")}}n.n=function(a){u.n(this.b,a);return this};n.v=function(a){u.v(this.b,a);return this};n.show=function(){this.b.style.display="block";return this};n.u=function(){this.b.style.display="none";return this};n.ja=function(){this.v("vjs-fade-out");this.n("vjs-fade-in");return this};
n.Ca=function(){this.v("vjs-fade-in");this.n("vjs-fade-out");return this};n.fb=function(){var a=this.b.style;a.display="block";a.opacity=1;a.$b="visible";return this};function ha(a){a=a.b.style;a.display="";a.opacity="";a.$b=""}n.width=function(a,b){return ia(this,"width",a,b)};n.height=function(a,b){return ia(this,"height",a,b)};n.Bb=function(a,b){return this.width(a,f).height(b)};
function ia(a,b,d,e){if(d!==c)return a.b.style[b]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:d+"px",e||a.h("resize"),a;if(!a.b)return 0;d=a.b.style[b];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.b["offset"+u.J(b)],10)};function v(a,b,d){this.I=a;var e={};u.t(e,u.options);u.t(e,ja(a));u.t(e,b);this.o={};y.call(this,this,e,d);this.A("play",function(a){u.h(this.b,{type:"firstplay",target:this.b})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())});this.e("ended",this.Lb);this.e("play",this.Ma);this.e("pause",this.La);this.e("progress",this.Mb);this.e("durationchange",this.Kb);this.e("error",this.Ja);u.Q[this.L]=this}t(v,y);n=v.prototype;
n.m=function(){u.Q[this.L]=h;this.I&&this.I.player&&(this.I.player=h);this.b&&this.b.player&&(this.b.player=h);clearInterval(this.sa);this.ea();this.j&&this.j.m();v.i.m.call(this)};function ja(a){var b={sources:[],tracks:[]};u.t(b,u.O(a));if(a.hasChildNodes())for(var d,e=a.childNodes,g=0,p=e.length;g<p;g++)a=e[g],d=a.nodeName.toLowerCase(),"source"===d?b.sources.push(u.O(a)):"track"===d&&b.tracks.push(u.O(a));return b}
n.d=function(){var a=this.b=v.i.d.call(this,"div"),b=this.I;b.removeAttribute("controls");b.removeAttribute("poster");b.removeAttribute("width");b.removeAttribute("height");if(b.hasChildNodes())for(var d=b.childNodes.length,e=0,g=b.childNodes;e<d;e++)("source"==g[0].nodeName.toLowerCase()||"track"==g[0].nodeName.toLowerCase())&&b.removeChild(g[0]);b.id=b.id||"vjs_video_"+u.q++;a.id=b.id;a.className=b.className;b.id+="_html5_api";b.className="vjs-tech";b.player=a.player=this;this.n("vjs-paused");this.width(this.f.width,
f);this.height(this.f.height,f);b.parentNode&&b.parentNode.insertBefore(a,b);u.W(b,a);return a};
function ka(a,b,d){a.j?la(a):"Html5"!==b&&a.I&&(a.b.removeChild(a.I),a.I=h);a.R=b;a.X=j;var e=u.t({source:d,qc:a.b},a.f[b.toLowerCase()]);d&&(d.src==a.o.src&&0<a.o.currentTime&&(e.startTime=a.o.currentTime),a.o.src=d.src);a.j=new window.videojs[b](a,e);z(a.j,function(){A(this.a);if(!this.F.Oa){var a=this.a;a.Ha=f;a.sa=setInterval(u.bind(a,function(){this.o.ya<this.buffered().end(0)?this.h("progress"):1==ma(this)&&(clearInterval(this.sa),this.h("progress"))}),500);a.j.A("progress",function(){this.F.Oa=
f;var a=this.a;a.Ha=j;clearInterval(a.sa)})}this.F.Ra||(a=this.a,a.Ia=f,a.e("play",a.lb),a.e("pause",a.ea),a.j.A("timeupdate",function(){this.F.Ra=f;na(this.a)}))})}function la(a){a.j.m();a.Ha&&(a.Ha=j,clearInterval(a.sa));a.Ia&&na(a);a.j=j}function na(a){a.Ia=j;a.ea();a.k("play",a.lb);a.k("pause",a.ea)}n.lb=function(){this.Ya&&this.ea();this.Ya=setInterval(u.bind(this,function(){this.h("timeupdate")}),250)};n.ea=function(){clearInterval(this.Ya)};
n.Lb=function(){this.f.loop&&(this.currentTime(0),this.play())};n.Ma=function(){u.v(this.b,"vjs-paused");u.n(this.b,"vjs-playing")};n.La=function(){u.v(this.b,"vjs-playing");u.n(this.b,"vjs-paused")};n.Mb=function(){1==ma(this)&&this.h("loadedalldata")};n.Kb=function(){this.duration(B(this,"duration"))};n.Ja=function(a){u.log("Video Error",a)};function C(a,b,d){if(a.j&&a.j.X)z(a.j,function(){this[b](d)});else try{a.j[b](d)}catch(e){u.log(e)}}
function B(a,b){if(a.j.X)try{return a.j[b]()}catch(d){if(a.j[b]===c)u.log("Video.js: "+b+" method not defined for "+a.R+" playback technology.",d);else{if("TypeError"==d.name)throw u.log("Video.js: "+b+" unavailable on "+a.R+" playback technology element.",d),a.j.X=j,d;u.log(d)}}}n.play=function(){var a={type:"play",target:this.b};this.h(a);a.la()||C(this,"play");return this};n.pause=function(){C(this,"pause");return this};n.paused=function(){return B(this,"paused")===j?j:f};
n.currentTime=function(a){return a!==c?(this.o.oc=a,C(this,"setCurrentTime",a),this.Ia&&this.h("timeupdate"),this):this.o.currentTime=B(this,"currentTime")||0};n.duration=function(a){return a!==c?(this.o.duration=parseFloat(a),this):this.o.duration};n.buffered=function(){var a=B(this,"buffered"),b=this.o.ya=this.o.ya||0;a&&(0<a.length&&a.end(0)!==b)&&(b=a.end(0),this.o.ya=b);return u.Aa(b)};function ma(a){return a.duration()?a.buffered().end(0)/a.duration():0}
n.volume=function(a){if(a!==c)return a=Math.max(0,Math.min(1,parseFloat(a))),this.o.volume=a,C(this,"setVolume",a),u.Tb(a),this;a=parseFloat(B(this,"volume"));return isNaN(a)?1:a};n.muted=function(a){return a!==c?(C(this,"setMuted",a),this):B(this,"muted")||j};n.va=function(){return B(this,"supportsFullScreen")||j};
n.ua=function(){var a=u.Qa.ua;this.P=f;a?(u.e(document,a.V,u.bind(this,function(){this.P=document[a.P];this.P===j&&u.k(document,a.V,arguments.callee);this.h("fullscreenchange")})),this.j.F.ab===j&&this.f.flash.iFrameMode!==f&&(this.pause(),la(this),u.e(document,a.V,u.bind(this,function(){u.k(document,a.V,arguments.callee);ka(this,this.R,{src:this.o.src})}))),this.b[a.Pb]()):this.j.va()?(this.h("fullscreenchange"),C(this,"enterFullScreen")):(this.h("fullscreenchange"),this.Gb=f,this.Cb=document.documentElement.style.overflow,
u.e(document,"keydown",u.bind(this,this.$a)),document.documentElement.style.overflow="hidden",u.n(document.body,"vjs-full-window"),u.n(this.b,"vjs-fullscreen"),this.h("enterFullWindow"));return this};function oa(a){var b=u.Qa.ua;a.P=j;b?(a.j.F.ab===j&&a.f.flash.iFrameMode!==f&&(a.pause(),la(a),u.e(document,b.V,u.bind(a,function(){u.k(document,b.V,arguments.callee);ka(this,this.R,{src:this.o.src})}))),document[b.zb]()):(a.j.va()?C(a,"exitFullScreen"):pa(a),a.h("fullscreenchange"))}
n.$a=function(a){27===a.keyCode&&(this.P===f?oa(this):pa(this))};function pa(a){a.Gb=j;u.k(document,"keydown",a.$a);document.documentElement.style.overflow=a.Cb;u.v(document.body,"vjs-full-window");u.v(a.b,"vjs-fullscreen");a.h("exitFullWindow")}
n.src=function(a){if(a instanceof Array){var b;a:{b=a;for(var d=0,e=this.f.techOrder;d<e.length;d++){var g=u.J(e[d]),p=window.videojs[g];if(p.isSupported())for(var k=0,r=b;k<r.length;k++){var q=r[k];if(p.canPlaySource(q)){b={source:q,j:g};break a}}}b=j}b?(a=b.source,b=b.j,b==this.R?this.src(a):ka(this,b,a)):this.b.appendChild(u.d("p",{innerHTML:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://www.google.com/chrome">Google Chrome</a> or download the latest <a href="http://get.adobe.com/flashplayer/">Adobe Flash Player</a>.'}))}else a instanceof
Object?window.videojs[this.R].canPlaySource(a)?this.src(a.src):this.src([a]):(this.o.src=a,this.X?(C(this,"src",a),"auto"==this.f.preload&&this.load(),this.f.autoplay&&this.play()):z(this,function(){this.src(a)}));return this};n.load=function(){C(this,"load");return this};n.currentSrc=function(){return B(this,"currentSrc")||this.o.src||""};n.da=function(a){return a!==c?(C(this,"setPreload",a),this.f.preload=a,this):B(this,"preload")};
n.autoplay=function(a){return a!==c?(C(this,"setAutoplay",a),this.f.autoplay=a,this):B(this,"autoplay")};n.loop=function(a){return a!==c?(C(this,"setLoop",a),this.f.loop=a,this):B(this,"loop")};n.poster=function(){return B(this,"poster")};n.error=function(){return B(this,"error")};var qa,ra,sa,ta;
if(document.gc!==c)qa="requestFullscreen",ra="exitFullscreen",sa="fullscreenchange",ta="fullScreen";else for(var ua=["moz","webkit"],va=ua.length-1;0<=va;va--){var D=ua[va];if(("moz"!=D||document.mozFullScreenEnabled)&&document[D+"CancelFullScreen"]!==c)qa=D+"RequestFullScreen",ra=D+"CancelFullScreen",sa=D+"fullscreenchange",ta="webkit"==D?D+"IsFullScreen":D+"FullScreen"}qa&&(u.Qa.ua={Pb:qa,zb:ra,V:sa,P:ta});
function wa(a,b,d){y.call(this,a,b,d);if(!a.f.sources||0===a.f.sources.length){b=0;for(d=a.f.techOrder;b<d.length;b++){var e=u.J(d[b]),g=window.videojs[e];if(g&&g.isSupported()){ka(a,e);break}}}else a.src(a.f.sources)}t(wa,y);function E(a,b){y.call(this,a,b)}t(E,y);E.prototype.z=function(){return"vjs-control "+E.i.z.call(this)};function F(a,b){y.call(this,a,b);a.A("play",u.bind(this,function(){this.ja();this.a.e("mouseover",u.bind(this,this.ja));this.a.e("mouseout",u.bind(this,this.Ca))}))}t(F,y);n=F.prototype;n.f={pc:"play",children:{playToggle:{},fullscreenToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},progressControl:{},volumeControl:{},muteToggle:{}}};
n.d=function(){return u.d("div",{className:"vjs-control-bar"})};n.ja=function(){F.i.ja.call(this);this.a.h("controlsvisible")};n.Ca=function(){F.i.Ca.call(this);this.a.h("controlshidden")};n.fb=function(){this.b.style.opacity="1"};function G(a,b){y.call(this,a,b);this.e("click",this.l);this.e("focus",this.pa);this.e("blur",this.oa)}t(G,E);n=G.prototype;
n.d=function(a,b){b=u.t({className:this.z(),innerHTML:'<div><span class="vjs-control-text">'+(this.M||"Need Text")+"</span></div>",Qb:"button",tabIndex:0},b);return G.i.d.call(this,a,b)};n.l=function(){};n.pa=function(){u.e(document,"keyup",u.bind(this,this.ca))};n.ca=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.l()};n.oa=function(){u.k(document,"keyup",u.bind(this,this.ca))};function H(a,b){G.call(this,a,b)}t(H,G);H.prototype.M="Play";
H.prototype.z=function(){return"vjs-play-button "+H.i.z.call(this)};H.prototype.l=function(){this.a.play()};function I(a,b){G.call(this,a,b)}t(I,G);I.prototype.M="Play";I.prototype.z=function(){return"vjs-pause-button "+I.i.z.call(this)};I.prototype.l=function(){this.a.pause()};function xa(a,b){G.call(this,a,b);a.e("play",u.bind(this,this.Ma));a.e("pause",u.bind(this,this.La))}t(xa,G);n=xa.prototype;n.M="Play";n.z=function(){return"vjs-play-control "+xa.i.z.call(this)};
n.l=function(){this.a.paused()?this.a.play():this.a.pause()};n.Ma=function(){u.v(this.b,"vjs-paused");u.n(this.b,"vjs-playing")};n.La=function(){u.v(this.b,"vjs-playing");u.n(this.b,"vjs-paused")};function J(a,b){G.call(this,a,b)}t(J,G);J.prototype.M="Fullscreen";J.prototype.z=function(){return"vjs-fullscreen-control "+J.i.z.call(this)};J.prototype.l=function(){this.a.P?oa(this.a):this.a.ua()};function K(a,b){G.call(this,a,b);a.e("play",u.bind(this,this.u));a.e("ended",u.bind(this,this.show))}
t(K,G);K.prototype.d=function(){return K.i.d.call(this,"div",{className:"vjs-big-play-button",innerHTML:"<span></span>"})};K.prototype.l=function(){this.a.currentTime()&&this.a.currentTime(0);this.a.play()};
function L(a,b){y.call(this,a,b);a.e("canplay",u.bind(this,this.u));a.e("canplaythrough",u.bind(this,this.u));a.e("playing",u.bind(this,this.u));a.e("seeked",u.bind(this,this.u));a.e("seeking",u.bind(this,this.show));a.e("seeked",u.bind(this,this.u));a.e("error",u.bind(this,this.show));a.e("waiting",u.bind(this,this.show))}t(L,y);
L.prototype.d=function(){var a,b;"string"==typeof this.a.g().style.WebkitBorderRadius||"string"==typeof this.a.g().style.MozBorderRadius||"string"==typeof this.a.g().style.dc||"string"==typeof this.a.g().style.fc?(a="vjs-loading-spinner",b='<div class="ball1"></div><div class="ball2"></div><div class="ball3"></div><div class="ball4"></div><div class="ball5"></div><div class="ball6"></div><div class="ball7"></div><div class="ball8"></div>'):(a="vjs-loading-spinner-fallback",b="");return L.i.d.call(this,
"div",{className:a,innerHTML:b})};function M(a,b){y.call(this,a,b);a.e("timeupdate",u.bind(this,this.ga))}t(M,y);M.prototype.d=function(){var a=M.i.d.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.content=u.d("div",{className:"vjs-current-time-display",innerHTML:"0:00"});a.appendChild(u.d("div").appendChild(this.content));return a};M.prototype.ga=function(){var a=this.a.hb?this.a.o.currentTime:this.a.currentTime();this.content.innerHTML=u.p(a,this.a.duration())};
function N(a,b){y.call(this,a,b);a.e("timeupdate",u.bind(this,this.ga))}t(N,y);N.prototype.d=function(){var a=N.i.d.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.content=u.d("div",{className:"vjs-duration-display",innerHTML:"0:00"});a.appendChild(u.d("div").appendChild(this.content));return a};N.prototype.ga=function(){this.a.duration()&&(this.content.innerHTML=u.p(this.a.duration()))};function ya(a,b){y.call(this,a,b)}t(ya,y);
ya.prototype.d=function(){return ya.i.d.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};function za(a,b){y.call(this,a,b);a.e("timeupdate",u.bind(this,this.ga))}t(za,y);za.prototype.d=function(){var a=za.i.d.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.content=u.d("div",{className:"vjs-remaining-time-display",innerHTML:"-0:00"});a.appendChild(u.d("div").appendChild(this.content));return a};
za.prototype.ga=function(){this.a.duration()&&(this.content.innerHTML="-"+u.p(this.a.duration()-this.a.currentTime()))};function O(a,b){y.call(this,a,b);this.wb=this.H[this.f.barName];this.handle=this.H[this.f.handleName];a.e(this.gb,u.bind(this,this.update));this.e("mousedown",this.Ka);this.e("focus",this.pa);this.e("blur",this.oa);this.a.e("controlsvisible",u.bind(this,this.update));z(a,u.bind(this,this.update))}t(O,y);n=O.prototype;
n.d=function(a,b){b=u.t({Qb:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},b);return O.i.d.call(this,a,b)};n.Ka=function(a){a.preventDefault();u.xb();u.e(document,"mousemove",u.bind(this,this.qa));u.e(document,"mouseup",u.bind(this,this.ra));this.qa(a)};n.ra=function(){u.Yb();u.k(document,"mousemove",this.qa,j);u.k(document,"mouseup",this.ra,j);this.update()};
n.update=function(){var a,b=this.bb(),d=this.handle,e=this.wb;isNaN(b)&&(b=0);a=b;if(d){a=this.b.offsetWidth;var g=d.g().offsetWidth;a=g?g/a:0;b*=1-a;a=b+a/2;d.g().style.left=u.round(100*b,2)+"%"}e.g().style.width=u.round(100*a,2)+"%"};function Aa(a,b){var d=a.b,e=u.Eb(d),d=d.offsetWidth,g=a.handle;g&&(g=g.g().offsetWidth,e+=g/2,d-=g);return Math.max(0,Math.min(1,(b.pageX-e)/d))}n.pa=function(){u.e(document,"keyup",u.bind(this,this.ca))};
n.ca=function(a){37==a.which?(a.preventDefault(),this.jb()):39==a.which&&(a.preventDefault(),this.kb())};n.oa=function(){u.k(document,"keyup",u.bind(this,this.ca))};function Ba(a,b){y.call(this,a,b)}t(Ba,y);Ba.prototype.f={children:{seekBar:{}}};Ba.prototype.d=function(){return Ba.i.d.call(this,"div",{className:"vjs-progress-control vjs-control"})};function P(a,b){O.call(this,a,b)}t(P,O);n=P.prototype;n.f={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};
n.gb="timeupdate";n.d=function(){return P.i.d.call(this,"div",{className:"vjs-progress-holder"})};n.bb=function(){return this.a.currentTime()/this.a.duration()};n.Ka=function(a){P.i.Ka.call(this,a);this.a.hb=f;this.Zb=!this.a.paused();this.a.pause()};n.qa=function(a){a=Aa(this,a)*this.a.duration();a==this.a.duration()&&(a-=0.1);this.a.currentTime(a)};n.ra=function(a){P.i.ra.call(this,a);this.a.hb=j;this.Zb&&this.a.play()};n.kb=function(){this.a.currentTime(this.a.currentTime()+1)};
n.jb=function(){this.a.currentTime(this.a.currentTime()-1)};function Ca(a,b){y.call(this,a,b);a.e("progress",u.bind(this,this.update))}t(Ca,y);Ca.prototype.d=function(){return Ca.i.d.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};Ca.prototype.update=function(){this.b.style&&(this.b.style.width=u.round(100*ma(this.a),2)+"%")};function Da(a,b){y.call(this,a,b)}t(Da,y);
Da.prototype.d=function(){return Da.i.d.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};function Ea(a,b){y.call(this,a,b)}t(Ea,y);Ea.prototype.d=function(){return Ea.i.d.call(this,"div",{className:"vjs-seek-handle",innerHTML:'<span class="vjs-control-text">00:00</span>'})};function Fa(a,b){y.call(this,a,b)}t(Fa,y);Fa.prototype.f={children:{volumeBar:{}}};Fa.prototype.d=function(){return Fa.i.d.call(this,"div",{className:"vjs-volume-control vjs-control"})};
function Ga(a,b){O.call(this,a,b)}t(Ga,O);n=Ga.prototype;n.f={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};n.gb="volumechange";n.d=function(){return Ga.i.d.call(this,"div",{className:"vjs-volume-bar"})};n.qa=function(a){this.a.volume(Aa(this,a))};n.bb=function(){return this.a.volume()};n.kb=function(){this.a.volume(this.a.volume()+0.1)};n.jb=function(){this.a.volume(this.a.volume()-0.1)};function Ha(a,b){y.call(this,a,b)}t(Ha,y);
Ha.prototype.d=function(){return Ha.i.d.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};function Ia(a,b){y.call(this,a,b)}t(Ia,y);Ia.prototype.d=function(){return Ia.i.d.call(this,"div",{className:"vjs-volume-handle",innerHTML:'<span class="vjs-control-text"></span>'})};function Q(a,b){G.call(this,a,b);a.e("volumechange",u.bind(this,this.update))}t(Q,G);
Q.prototype.d=function(){return Q.i.d.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};Q.prototype.l=function(){this.a.muted(this.a.muted()?j:f)};Q.prototype.update=function(){var a=this.a.volume(),b=3;0===a||this.a.muted()?b=0:0.33>a?b=1:0.67>a&&(b=2);for(a=0;4>a;a++)u.v(this.b,"vjs-vol-"+a);u.n(this.b,"vjs-vol-"+b)};function Ja(a,b){G.call(this,a,b);this.a.f.poster||this.u();a.e("play",u.bind(this,this.u))}t(Ja,G);
Ja.prototype.d=function(){var a=u.d("img",{className:"vjs-poster",tabIndex:-1});this.a.f.poster&&(a.src=this.a.f.poster);return a};Ja.prototype.l=function(){this.a.play()};function R(a,b){y.call(this,a,b)}t(R,y);function Ka(a,b){a.G(b);b.e("click",u.bind(a,function(){ha(this)}))}R.prototype.d=function(){return R.i.d.call(this,"ul",{className:"vjs-menu"})};function S(a,b){G.call(this,a,b);b.selected&&this.n("vjs-selected")}t(S,G);
S.prototype.d=function(a,b){return S.i.d.call(this,"li",u.t({className:"vjs-menu-item",innerHTML:this.f.label},b))};S.prototype.l=function(){this.selected(f)};S.prototype.selected=function(a){a?this.n("vjs-selected"):this.v("vjs-selected")};function T(a,b,d){y.call(this,a,b,d)}t(T,y);T.prototype.l=function(){this.a.f.controls&&(this.a.paused()?this.a.play():this.a.pause())};u.media={};u.media.wa="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function La(){var a=u.media.wa[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=u.media.wa.length-1;0<=i;i--)T.prototype[u.media.wa[i]]=La();function U(a,b,d){y.call(this,a,b,d);(b=b.source)&&this.b.currentSrc==b.src?a.h("loadstart"):b&&(this.b.src=b.src);z(a,function(){this.f.autoplay&&this.paused()&&(this.I.poster=h,this.play())});this.e("click",this.l);for(a=Ma.length-1;0<=a;a--)u.e(this.b,Ma[a],u.bind(this.a,this.Db));A(this)}t(U,T);n=U.prototype;n.m=function(){U.i.m.call(this)};
n.d=function(){var a=this.a,b=a.I;if(!b||this.F.Ib===j)b&&a.g().removeChild(b),b=u.createElement("video",{id:b.id||a.id()+"_html5_api",className:b.className||"vjs-tech"}),u.W(b,a.g());for(var d=["autoplay","preload","loop","muted"],e=d.length-1;0<=e;e--){var g=d[e];a.f[g]!==h&&(b[g]=a.f[g])}return b};n.Db=function(a){"play"!==a.type&&(this.h(a),a.stopPropagation())};n.play=function(){this.b.play()};n.pause=function(){this.b.pause()};n.paused=function(){return this.b.paused};n.currentTime=function(){return this.b.currentTime};
n.Sb=function(a){try{this.b.currentTime=a}catch(b){u.log(b,"Video is not ready. (Video.js)")}};n.duration=function(){return this.b.duration||0};n.buffered=function(){return this.b.buffered};n.volume=function(){return this.b.volume};n.Xb=function(a){this.b.volume=a};n.muted=function(){return this.b.muted};n.Vb=function(a){this.b.muted=a};n.width=function(){return this.b.offsetWidth};n.height=function(){return this.b.offsetHeight};
n.va=function(){return"function"==typeof this.b.webkitEnterFullScreen&&!navigator.userAgent.match("Chrome")&&!navigator.userAgent.match("Mac OS X 10.5")?f:j};n.src=function(a){this.b.src=a};n.load=function(){this.b.load()};n.currentSrc=function(){return this.b.currentSrc};n.da=function(){return this.b.da};n.Wb=function(a){this.b.da=a};n.autoplay=function(){return this.b.autoplay};n.Rb=function(a){this.b.autoplay=a};n.loop=function(){return this.b.loop};n.Ub=function(a){this.b.loop=a};n.error=function(){return this.b.error};
var Ma="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");U.prototype.F={kc:u.tb.webkitEnterFullScreen?!u.C.match("Chrome")&&!u.C.match("Mac OS X 10.5")?f:j:j,Ib:!u.pb};u.nb&&3>u.mb&&(document.createElement("video").constructor.prototype.canPlayType=function(a){return a&&-1!=a.toLowerCase().indexOf("video/mp4")?"maybe":""});function V(a,b,d){y.call(this,a,b,d);var e=b.source,g=b.parentEl;d=this.b=u.d("div",{id:a.id()+"_temp_flash"});var p=a.id()+"_flash_api";a=a.f;var k=u.t({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.da,loop:a.loop,muted:a.muted},b.flashVars),r=u.t({wmode:"opaque",bgcolor:"#000000"},b.params),q=u.t({id:p,name:p,"class":"vjs-tech"},b.attributes);e&&(k.src=encodeURIComponent(u.ka(e.src)));
u.W(d,g);b.startTime&&z(this,function(){this.load();this.play();this.currentTime(b.startTime)});if(b.iFrameMode===f&&!u.ob){var w=u.d("iframe",{id:p+"_iframe",name:p+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});k.readyFunction="ready";k.eventProxyFunction="events";k.errorEventProxyFunction="errors";u.e(w,"load",u.bind(this,function(){var a,d=w.contentWindow;a=w.contentDocument?w.contentDocument:w.contentWindow.document;a.write(Na(b.swf,k,r,q));d.player=
this.a;d.ready=u.bind(this.a,function(b){b=a.getElementById(b);var d=this.j;d.b=b;u.e(b,"click",d.bind(d.l));Oa(d)});d.events=u.bind(this.a,function(a,b){this&&"flash"===this.R&&this.h(b)});d.errors=u.bind(this.a,function(a,b){u.log("Flash Error",b)})}));d.parentNode.replaceChild(w,d)}else{a=Na(b.swf,k,r,q);a=u.d("div",{innerHTML:a}).childNodes[0];e=d.parentNode;d.parentNode.replaceChild(a,d);var hb=e.childNodes[0];setTimeout(function(){hb.style.display="block"},1E3)}}t(V,T);n=V.prototype;n.m=function(){V.i.m.call(this)};
n.play=function(){this.b.vjs_play()};n.pause=function(){this.b.vjs_pause()};n.src=function(a){a=u.ka(a);this.b.vjs_src(a);if(this.a.autoplay()){var b=this;setTimeout(function(){b.play()},0)}};n.load=function(){this.b.vjs_load()};n.poster=function(){this.b.vjs_getProperty("poster")};n.buffered=function(){return u.Aa(this.b.vjs_getProperty("buffered"))};n.va=m(j);
var Pa=V.prototype,Qa="preload currentTime defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),Ra="error currentSrc networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");function Sa(){var a=Qa[i],b=a.charAt(0).toUpperCase()+a.slice(1);Pa["set"+b]=function(b){return this.b.vjs_setProperty(a,b)}}
function Ta(a){Pa[a]=function(){return this.b.vjs_getProperty(a)}}for(i=0;i<Qa.length;i++)Ta(Qa[i]),Sa();for(i=0;i<Ra.length;i++)Ta(Ra[i]);V.prototype.F={Fb:{"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"},Oa:j,Ra:j,ab:j,rc:!u.C.match("Firefox")};V.onReady=function(a){a=u.g(a);var b=a.player||a.parentNode.player,d=b.j;a.player=b;d.b=a;d.e("click",d.l);Oa(d)};function Oa(a){a.g().vjs_getProperty?A(a):setTimeout(function(){Oa(a)},50)}V.onEvent=function(a,b){"play"!==b&&u.g(a).player.h(b)};
V.onError=function(a,b){u.g(a).player.h("error");u.log("Flash Error",b,a)};function Na(a,b,d,e){var g="",p="",k="";b&&u.U(b,function(a,b){g+=a+"="+b+"&amp;"});d=u.t({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);u.U(d,function(a,b){p+='<param name="'+a+'" value="'+b+'" />'});e=u.t({data:a,width:"100%",height:"100%"},e);u.U(e,function(a,b){k+=a+'="'+b+'" '});return'<object type="application/x-shockwave-flash"'+k+">"+p+"</object>"};function W(a){a.fa=a.fa||[];return a.fa}function Ua(a,b,d){for(var e=a.fa,g=0,p=e.length,k,r;g<p;g++)k=e[g],k.id()===b?(k.show(),r=k):d&&(k.B()==d&&0<k.mode())&&k.disable();(b=r?r.B():d?d:j)&&a.h(b+"trackchange")}function X(a,b){y.call(this,a,b);this.L=b.id||"vjs_"+b.kind+"_"+b.language+"_"+u.q++;this.ib=b.src;this.Ab=b["default"]||b.dflt;this.uc=b.title;this.nc=b.srclang;this.Hb=b.label;this.T=[];this.Ua=[];this.Z=this.$=0}t(X,y);n=X.prototype;n.B=l("s");n.src=l("ib");n.Ba=l("Ab");n.label=l("Hb");
n.readyState=l("$");n.mode=l("Z");n.d=function(){return X.i.d.call(this,"div",{className:"vjs-"+this.s+" vjs-text-track"})};n.show=function(){Va(this);this.Z=2;X.i.show.call(this)};n.u=function(){Va(this);this.Z=1;X.i.u.call(this)};n.disable=function(){2==this.Z&&this.u();this.a.k("timeupdate",u.bind(this,this.update,this.L));this.a.k("ended",u.bind(this,this.reset,this.L));this.reset();this.a.H.textTrackDisplay.removeChild(this);this.Z=0};
function Va(a){0===a.$&&a.load();0===a.Z&&(a.a.e("timeupdate",u.bind(a,a.update,a.L)),a.a.e("ended",u.bind(a,a.reset,a.L)),("captions"===a.s||"subtitles"===a.s)&&a.a.H.textTrackDisplay.G(a))}n.load=function(){0===this.$&&(this.$=1,u.get(this.ib,u.bind(this,this.Nb),u.bind(this,this.Ja)))};n.Ja=function(a){this.error=a;this.$=3;this.h("error")};
n.Nb=function(a){var b,d;a=a.split("\n");for(var e="",g=1,p=a.length;g<p;g++)if(e=u.trim(a[g])){-1==e.indexOf("--\x3e")?(b=e,e=u.trim(a[++g])):b=this.T.length;b={id:b,index:this.T.length};d=e.split(" --\x3e ");b.startTime=Wa(d[0]);b.aa=Wa(d[1]);for(d=[];a[++g]&&(e=u.trim(a[g]));)d.push(e);b.text=d.join("<br/>");this.T.push(b)}this.$=2;this.h("loaded")};
function Wa(a){var b=a.split(":");a=0;var d,e,g;3==b.length?(d=b[0],e=b[1],b=b[2]):(d=0,e=b[0],b=b[1]);b=b.split(/\s+/);b=b.splice(0,1)[0];b=b.split(/\.|,/);g=parseFloat(b[1]);b=b[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(b);g&&(a+=g/1E3);return a}
n.update=function(){if(0<this.T.length){var a=this.a.currentTime();if(this.Na===c||a<this.Na||this.na<=a){var b=this.T,d=this.a.duration(),e=0,g=j,p=[],k,r,q,w;a>=this.na||this.na===c?w=this.Da!==c?this.Da:0:(g=f,w=this.Ga!==c?this.Ga:b.length-1);for(;;){q=b[w];if(q.aa<=a)e=Math.max(e,q.aa),q.ha&&(q.ha=j);else if(a<q.startTime){if(d=Math.min(d,q.startTime),q.ha&&(q.ha=j),!g)break}else g?(p.splice(0,0,q),r===c&&(r=w),k=w):(p.push(q),k===c&&(k=w),r=w),d=Math.min(d,q.aa),e=Math.max(e,q.startTime),q.ha=
f;if(g)if(0===w)break;else w--;else if(w===b.length-1)break;else w++}this.Ua=p;this.na=d;this.Na=e;this.Da=k;this.Ga=r;a=this.Ua;b="";d=0;for(e=a.length;d<e;d++)b+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.b.innerHTML=b;this.h("cuechange")}}};n.reset=function(){this.na=0;this.Na=this.a.duration();this.Ga=this.Da=0};function Xa(a,b){X.call(this,a,b)}t(Xa,X);Xa.prototype.s="captions";function Ya(a,b){X.call(this,a,b)}t(Ya,X);Ya.prototype.s="subtitles";function Za(a,b){X.call(this,a,b)}
t(Za,X);Za.prototype.s="chapters";function $a(a,b,d){y.call(this,a,b,d);if(a.f.tracks&&0<a.f.tracks.length){b=this.a;a=a.f.tracks;var e;for(d=0;d<a.length;d++){e=a[d];var g=b,p=e.kind,k=e.label,r=e.language,q=e;e=g.fa=g.fa||[];q=q||{};q.kind=p;q.label=k;q.language=r;p=u.J(p||"subtitles");g=new window.videojs[p+"Track"](g,q);e.push(g)}}}t($a,y);$a.prototype.d=function(){return $a.i.d.call(this,"div",{className:"vjs-text-track-display"})};
function Y(a,b){var d=this.S=b.track;b.label=d.label();b.selected=d.Ba();S.call(this,a,b);this.a.e(d.B()+"trackchange",u.bind(this,this.update))}t(Y,S);Y.prototype.l=function(){Y.i.l.call(this);Ua(this.a,this.S.id(),this.S.B())};Y.prototype.update=function(){2==this.S.mode()?this.selected(f):this.selected(j)};function ab(a,b){b.track={B:function(){return b.kind},Ob:a,label:m("Off"),Ba:m(j),mode:m(j)};Y.call(this,a,b)}t(ab,Y);ab.prototype.l=function(){ab.i.l.call(this);Ua(this.a,this.S.id(),this.S.B())};
ab.prototype.update=function(){for(var a=W(this.a),b=0,d=a.length,e,g=f;b<d;b++)e=a[b],e.B()==this.S.B()&&2==e.mode()&&(g=j);g?this.selected(f):this.selected(j)};function Z(a,b){G.call(this,a,b);this.Y=this.za();0===this.ba.length&&this.u()}t(Z,G);n=Z.prototype;n.za=function(){var a=new R(this.a);a.g().appendChild(u.d("li",{className:"vjs-menu-title",innerHTML:u.J(this.s)}));Ka(a,new ab(this.a,{kind:this.s}));this.ba=this.Xa();for(var b=0;b<this.ba.length;b++)Ka(a,this.ba[b]);this.G(a);return a};
n.Xa=function(){for(var a=[],b,d=0;d<W(this.a).length;d++)b=W(this.a)[d],b.B()===this.s&&a.push(new Y(this.a,{track:b}));return a};n.z=function(){return this.className+" vjs-menu-button "+Z.i.z.call(this)};n.pa=function(){this.Y.fb();u.A(this.Y.b.childNodes[this.Y.b.childNodes.length-1],"blur",u.bind(this,function(){ha(this.Y)}))};n.oa=function(){};n.l=function(){this.A("mouseout",u.bind(this,function(){ha(this.Y);this.b.blur()}))};function bb(a,b){Z.call(this,a,b)}t(bb,Z);bb.prototype.s="captions";
bb.prototype.M="Captions";bb.prototype.className="vjs-captions-button";function cb(a,b){Z.call(this,a,b)}t(cb,Z);cb.prototype.s="subtitles";cb.prototype.M="Subtitles";cb.prototype.className="vjs-subtitles-button";function db(a,b){Z.call(this,a,b)}t(db,Z);n=db.prototype;n.s="chapters";n.M="Chapters";n.className="vjs-chapters-button";n.Xa=function(){for(var a=[],b,d=0;d<W(this.a).length;d++)b=W(this.a)[d],b.B()===this.s&&a.push(new Y(this.a,{track:b}));return a};
n.za=function(){for(var a=W(this.a),b=0,d=a.length,e,g,p=this.ba=[];b<d;b++)if(e=a[b],e.B()==this.s&&e.Ba()){if(2>e.readyState()){this.hc=e;e.e("loaded",u.bind(this,this.za));return}g=e;break}a=this.Y=new R(this.a);a.b.appendChild(u.d("li",{className:"vjs-menu-title",innerHTML:u.J(this.s)}));if(g){e=g.T;for(var k,b=0,d=e.length;b<d;b++)k=e[b],k=new eb(this.a,{track:g,cue:k}),p.push(k),a.G(k)}this.G(a);0<this.ba.length&&this.show();return a};
function eb(a,b){var d=this.S=b.track,e=this.cue=b.cue,g=a.currentTime();b.label=e.text;b.selected=e.startTime<=g&&g<e.aa;S.call(this,a,b);d.e("cuechange",u.bind(this,this.update))}t(eb,S);eb.prototype.l=function(){eb.i.l.call(this);this.a.currentTime(this.cue.startTime);this.update(this.cue.startTime)};eb.prototype.update=function(){var a=this.cue,b=this.a.currentTime();a.startTime<=b&&b<a.aa?this.selected(f):this.selected(j)};u.t(F.prototype.f.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});if(JSON&&"function"===JSON.parse)u.JSON=JSON;else{u.JSON={};var fb=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;u.JSON.parse=function(a,b){function d(a,e){var k,r,q=a[e];if(q&&"object"===typeof q)for(k in q)Object.prototype.hasOwnProperty.call(q,k)&&(r=d(q,k),r!==c?q[k]=r:delete q[k]);return b.call(a,e,q)}var e;a=String(a);fb.lastIndex=0;fb.test(a)&&(a=a.replace(fb,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?d({"":e},""):e;throw new SyntaxError("JSON.parse");}};u.xa=function(){var a,b,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((b=d[e])&&b.getAttribute)b.player===c&&(a=b.getAttribute("data-setup"),a!==h&&(a=u.JSON.parse(a||"{}"),x(b,a)));else{u.Va();break}else u.ac||u.Va()};u.Va=function(){setTimeout(u.xa,1)};u.A(window,"load",function(){u.ac=f});u.xa();s("videojs",u);s("_V_",u);s("videojs.options",u.options);s("videojs.cache",u.N);s("videojs.Component",y);y.prototype.dispose=y.prototype.m;y.prototype.createEl=y.prototype.d;y.prototype.getEl=y.prototype.mc;y.prototype.addChild=y.prototype.G;y.prototype.getChildren=y.prototype.lc;y.prototype.on=y.prototype.e;y.prototype.off=y.prototype.k;y.prototype.one=y.prototype.A;y.prototype.trigger=y.prototype.h;y.prototype.show=y.prototype.show;y.prototype.hide=y.prototype.u;y.prototype.width=y.prototype.width;
y.prototype.height=y.prototype.height;y.prototype.dimensions=y.prototype.Bb;s("videojs.Player",v);s("videojs.MediaLoader",wa);s("videojs.PosterImage",Ja);s("videojs.LoadingSpinner",L);s("videojs.BigPlayButton",K);s("videojs.ControlBar",F);s("videojs.TextTrackDisplay",$a);s("videojs.Control",E);s("videojs.ControlBar",F);s("videojs.Button",G);s("videojs.PlayButton",H);s("videojs.PauseButton",I);s("videojs.PlayToggle",xa);s("videojs.FullscreenToggle",J);s("videojs.BigPlayButton",K);
s("videojs.LoadingSpinner",L);s("videojs.CurrentTimeDisplay",M);s("videojs.DurationDisplay",N);s("videojs.TimeDivider",ya);s("videojs.RemainingTimeDisplay",za);s("videojs.Slider",O);s("videojs.ProgressControl",Ba);s("videojs.SeekBar",P);s("videojs.LoadProgressBar",Ca);s("videojs.PlayProgressBar",Da);s("videojs.SeekHandle",Ea);s("videojs.VolumeControl",Fa);s("videojs.VolumeBar",Ga);s("videojs.VolumeLevel",Ha);s("videojs.VolumeHandle",Ia);s("videojs.MuteToggle",Q);s("videojs.PosterImage",Ja);
s("videojs.Menu",R);s("videojs.MenuItem",S);s("videojs.SubtitlesButton",cb);s("videojs.CaptionsButton",bb);s("videojs.ChaptersButton",db);s("videojs.MediaTechController",T);s("videojs.Html5",U);U.Events=Ma;U.isSupported=function(){return!!document.createElement("video").canPlayType};U.canPlaySource=function(a){return!!document.createElement("video").canPlayType(a.type)};U.prototype.setCurrentTime=U.prototype.Sb;U.prototype.setVolume=U.prototype.Xb;U.prototype.setMuted=U.prototype.Vb;
U.prototype.setPreload=U.prototype.Wb;U.prototype.setAutoplay=U.prototype.Rb;U.prototype.setLoop=U.prototype.Ub;s("videojs.Flash",V);
V.isSupported=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(b){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return 10<=a.split(",")[0]};V.canPlaySource=function(a){if(a.type in V.prototype.F.Fb)return"maybe"};
V.onReady=V.onReady;s("videojs.TextTrack",X);X.prototype.label=X.prototype.label;s("videojs.CaptionsTrack",Xa);s("videojs.SubtitlesTrack",Ya);s("videojs.ChaptersTrack",Za);s("videojs.autoSetup",u.xa);module("Component");function $(){return{id:m("player_1")}}test("should create an element",function(){var a=new y($(),{});ok(a.g().nodeName)});test("should add a child component",function(){var a=new y($()),b=a.G("component");ok(1===a.children().length);ok(a.children()[0]===b);ok(a.g().childNodes[0]===b.g());ok(a.H.component===b);var d=ok,e=b.id();d(a.ia[e]===b)});
test("should init child coponents from options",function(){var a=new y($(),{children:{component:f}});ok(1===a.children().length);ok(1===a.g().childNodes.length)});
test("should do a deep merge of child options",function(){var a=ga(y.prototype,{children:{childOne:{foo:"bar",asdf:"fdsa"},childTwo:{},childThree:{}}},{children:{childOne:{foo:"baz",abc:"123"},childThree:h,childFour:{}}}).children;ok("baz"===a.childOne.foo,"value three levels deep overridden");ok("fdsa"===a.childOne.asdf,"value three levels deep maintained");ok("123"===a.childOne.abc,"value three levels deep added");ok(a.childTwo,"object two levels deep maintained");ok(a.childThree===h,"object two levels deep removed");
ok(a.childFour,"object two levels deep added")});test("should dispose of component and children",function(){var a=new y($()),b=a.G("Component");ok(1===a.children().length);a.e("click",m(f));var d=u.getData(a.g()),e=a.g()[u.expando];a.m();ok(!a.children(),"component children were deleted");ok(!a.g(),"component element was deleted");ok(!b.children(),"child children were deleted");ok(!b.g(),"child element was deleted");ok(!u.N[e],"listener cache nulled");ok(u.ma(d),"original listener cache object was emptied")});
test("should add and remove event listeners to element",function(){function a(){ok(f,"fired event once");ok(this===b,"listener has the component as context")}var b=new y($(),{});expect(2);b.e("test-event",a);b.h("test-event");b.k("test-event",a);b.h("test-event")});test("should trigger a listener once using one()",function(){var a=new y($(),{});expect(1);a.A("test-event",function(){ok(f,"fired event once")});a.h("test-event");a.h("test-event")});
test("should trigger a listener when ready",function(){expect(2);var a=new y($(),{},function(){ok(f,"options listener fired")});A(a);z(a,function(){ok(f,"ready method listener fired")});A(a)});test("should add and remove a CSS class",function(){var a=new y($(),{});a.n("test-class");ok(-1!==a.g().className.indexOf("test-class"));a.v("test-class");ok(-1===a.g().className.indexOf("test-class"))});
test("should show and hide an element",function(){var a=new y($(),{});a.u();ok("none"===a.g().style.display);a.show();ok("block"===a.g().style.display)});
test("should change the width and height of a component",function(){var a=document.createElement("div"),b=new y($(),{}),d=b.g();document.getElementById("qunit-fixture").appendChild(a);a.appendChild(d);a.style.width="1000px";a.style.height="1000px";b.width("50%");b.height("123px");ok(500===b.width(),"percent values working");ok(u.Ea(d,"width")===b.width()+"px","matches computed style");ok(123===b.height(),"px values working");b.width(321);ok(321===b.width(),"integer values working")});module("Core");test("should create a video tag and have access children in old IE",function(){document.getElementById("qunit-fixture").innerHTML+="<video id='test_vid_id'><source type='video/mp4'></video>";vid=document.getElementById("test_vid_id");ok(1===vid.childNodes.length);ok("video/mp4"===vid.childNodes[0].getAttribute("type"))});
test("should return a video player instance",function(){document.getElementById("qunit-fixture").innerHTML+="<video id='test_vid_id'></video><video id='test_vid_id2'></video>";var a=x("test_vid_id");ok(a,"created player from tag");ok("test_vid_id"===a.id());ok(x.Q.test_vid_id===a,"added player to global reference");var b=x("test_vid_id");ok(a===b,"did not create a second player from same tag");a=x(document.getElementById("test_vid_id2"));ok("test_vid_id2"===a.id(),"created player from element")});module("Events");test("should add and remove an event listener to an element",function(){function a(){ok(f,"Click Triggered")}expect(1);var b=document.createElement("div");u.e(b,"click",a);u.h(b,"click");u.k(b,"click",a);u.h(b,"click")});test("should remove all listeners of a type",function(){var a=document.createElement("div"),b=0;u.e(a,"click",function(){b++});u.e(a,"click",function(){b++});u.h(a,"click");ok(2===b,"both click listeners fired");u.k(a,"click");u.h(a,"click");ok(2===b,"no click listeners fired")});
test("should remove all listeners from an element",function(){expect(2);var a=document.createElement("div");u.e(a,"fake1",function(){ok(f,"Fake1 Triggered")});u.e(a,"fake2",function(){ok(f,"Fake2 Triggered")});u.h(a,"fake1");u.h(a,"fake2");u.k(a);u.h(a,"fake1");u.h(a,"fake2")});test("should listen only once",function(){expect(1);var a=document.createElement("div");u.A(a,"click",function(){ok(f,"Click Triggered")});u.h(a,"click");u.h(a,"click")});
test("should stop immediate propagtion",function(){expect(1);var a=document.createElement("div");u.e(a,"test",function(a){ok(f,"First listener fired");a.stopImmediatePropagation()});u.e(a,"test",function(){ok(j,"Second listener fired")});u.h(a,"test")});module("Lib");test("should create an element",function(){var a=u.d(),b=u.d("span",{"data-test":"asdf",innerHTML:"fdsa"});ok("DIV"===a.nodeName);ok("SPAN"===b.nodeName);ok("asdf"===b["data-test"]);ok("fdsa"===b.innerHTML)});test("should make a string start with an uppercase letter",function(){var a=u.J("bar");ok("Bar"===a)});test("should loop through each property on an object",function(){var a={ub:1,vb:2,c:3};u.U(a,function(b,d){a[b]=d+3});deepEqual(a,{ub:4,vb:5,c:6})});
test("should add context to a function",function(){var a={test:"obj"};u.bind(a,function(){ok(this===a)})()});test("should add and remove a class name on an element",function(){var a=document.createElement("div");u.n(a,"test-class");ok("test-class"===a.className,"class added");u.n(a,"test-class");ok("test-class"===a.className,"same class not duplicated");u.n(a,"test-class2");ok("test-class test-class2"===a.className,"added second class");u.v(a,"test-class");ok("test-class2"===a.className,"removed first class")});
test("should get and remove data from an element",function(){var a=document.createElement("div"),b=u.getData(a),d=a[u.expando];ok("object"===typeof b,"data object created");var e={ec:"fdsa"};b.test=e;ok(u.getData(a).test===e,"data added");u.Pa(a);ok(!u.N[d],"cached item nulled");ok(a[u.expando]===h||a[u.expando]===c,"element data id removed")});
test("should read tag attributes from elements, including HTML5 in all browsers",function(){var a=document.createElement("div"),b;b='<video id="vid1" controls autoplay loop muted preload="none" src="http://google.com" poster="http://www2.videojs.com/img/video-js-html5-video-player.png" data-test="asdf" data-empty-string=""></video><video id="vid2"><source id="source" src="http://google.com" type="video/mp4" media="fdsa" title="test" >';b+='<track id="track" default src="http://google.com" kind="captions" srclang="en" label="testlabel" title="test" >';
a.innerHTML+=b;document.getElementById("qunit-fixture").appendChild(a);a=u.O(document.getElementById("vid2"));b=u.O(document.getElementById("source"));var d=u.O(document.getElementById("track"));deepEqual(u.O(document.getElementById("vid1")),{autoplay:f,controls:f,"data-test":"asdf","data-empty-string":"",id:"vid1",loop:f,muted:f,poster:"http://www2.videojs.com/img/video-js-html5-video-player.png",preload:"none",src:"http://google.com"});deepEqual(a,{id:"vid2"});deepEqual(b,{title:"test",media:"fdsa",
type:"video/mp4",src:"http://google.com",id:"source"});deepEqual(d,{"default":f,id:"track",kind:"captions",label:"testlabel",src:"http://google.com",srclang:"en",title:"test"})});
test("should get the right style values for an element",function(){var a=document.createElement("div"),b=document.createElement("div"),d=document.getElementById("qunit-fixture");b.appendChild(a);d.appendChild(b);b.style.width="1000px";b.style.height="1000px";a.style.height="100%";a.style.width="123px";ok("1000px"===u.Ea(a,"height"));ok("123px"===u.Ea(a,"width"))});
test("should insert an element first in another",function(){var a=document.createElement("div"),b=document.createElement("div"),d=document.createElement("div");u.W(a,d);ok(d.firstChild===a,"inserts first into empty parent");u.W(b,d);ok(d.firstChild===b,"inserts first into parent with child")});
test("should return the element with the ID",function(){var a=document.createElement("div"),b=document.createElement("div"),d=document.getElementById("qunit-fixture");d.appendChild(a);d.appendChild(b);a.id="test_id1";b.id="test_id2";ok(u.g("test_id1")===a,"found element for ID");ok(u.g("#test_id2")===b,"found element for CSS ID")});test("should trim whitespace from a string",function(){ok("asdf asdf asdf"===u.trim(" asdf asdf asdf   \t\n\r"))});
test("should round a number",function(){ok(1===u.round(1.01));ok(2===u.round(1.5));ok(1.55===u.round(1.55,2));ok(10.55===u.round(10.551,2))});
test("should format time as a string",function(){ok("0:01"===u.p(1));ok("0:10"===u.p(10));ok("1:00"===u.p(60));ok("10:00"===u.p(600));ok("1:00:00"===u.p(3600));ok("10:00:00"===u.p(36E3));ok("100:00:00"===u.p(36E4));ok("0:01"===u.p(1,1));ok("0:01"===u.p(1,10));ok("0:01"===u.p(1,60));ok("00:01"===u.p(1,600));ok("0:00:01"===u.p(1,3600));ok("0:00:01"===u.p(1,36E3));ok("0:00:01"===u.p(1,36E4))});test("should create a fake timerange",function(){var a=u.Aa(10);ok(0===a.start());ok(10===a.end())});
test("should get an absolute URL",function(){ok("http://asdf.com"===u.ka("http://asdf.com"));ok("https://asdf.com/index.html"===u.ka("https://asdf.com/index.html"))});module("HTML5");u.w=function(a,b,d){y.call(this,a,b,d);A(this)};t(u.w,T);u.w.isSupported=m(f);u.w.yb=m(f);u.w.prototype.F={Oa:f,Ra:f};u.w.prototype.d=function(){var a=u.w.i.d.call(this,"div",{className:"vjs-tech"});u.W(a,this.a.g());return a};u.w.prototype.currentTime=m(0);u.w.prototype.volume=m(0);s("videojs.MediaFaker",u.w);u.w.isSupported=u.w.isSupported;u.w.canPlaySource=u.w.yb;module("Player");function gb(){var a=document.createElement("video");a.id="example_1";a.className="video-js vjs-default-skin";return a}function ib(a){var b=gb();document.getElementById("qunit-fixture").appendChild(b);a=u.t({techOrder:["mediaFaker"]},a);return player=new v(b,a)}test("should create player instance that inherits from component and dispose it",function(){var a=ib();ok("DIV"===a.g().nodeName);ok(a.e,"component function exists");a.m();ok(a.g()===h,"element disposed")});
test("should accept options from multiple sources and override in correct order",function(){u.options.attr=1;var a=gb(),a=new v(a);ok(1===a.f.attr,"global option was set");a.m();a=gb();a.setAttribute("attr","asdf");a=new v(a);ok("asdf"===a.f.attr,"Tag options overrode global options");a.m();a=gb();a.setAttribute("attr","asdf");a=new v(a,{attr:"fdsa"});ok("fdsa"===a.f.attr,"Init options overrode tag and global options");a.m()});
test("should get tag, source, and track settings",function(){var a=document.getElementById("qunit-fixture"),b;b='<video id="example_1" class="video-js" autoplay preload="metadata"><source src="http://google.com" type="video/mp4"><source src="http://google.com" type="video/webm">';b+='<track src="http://google.com" kind="captions" default>';b+="</video>";a.innerHTML+=b;a=document.getElementById("example_1");b=new v(a);ok(b.f.autoplay===f);ok("metadata"===b.f.preload);ok("example_1"===b.f.id);ok(2===
b.f.sources.length);ok("http://google.com"===b.f.sources[0].src);ok("video/mp4"===b.f.sources[0].type);ok("video/webm"===b.f.sources[1].type);ok(1===b.f.tracks.length);ok("captions"===b.f.tracks[0].kind);ok(b.f.tracks[0]["default"]===f);ok(-1!==b.g().className.indexOf("video-js"),"transferred class from tag to player div");ok("example_1"===b.g().id,"transferred id from tag to player div");ok(a.player===b,"player referenceable on original tag");ok(u.Q[b.id()]===b,"player referenceable from global list");
ok(a.id!==b.id,"tag ID no longer is the same as player ID");ok(a.className!==b.g().className,"tag classname updated");b.m();ok(a.player===h,"tag player ref killed");ok(!u.Q.example_1,"global player ref killed");ok(b.g()===h,"player el killed")});
test("should set the width and height of the player",function(){var a=ib({width:123,height:"100%"});ok(123===a.width());ok("123px"===a.g().style.width);var b=document.getElementById("qunit-fixture"),d=document.createElement("div");b.appendChild(d);d.appendChild(a.g());d.style.height="1000px";ok(1E3===a.height());a.m()});
test("should accept options from multiple sources and override in correct order",function(){var a=gb(),b=document.createElement("div"),d=document.getElementById("qunit-fixture");b.appendChild(a);d.appendChild(b);var d=new v(a),e=d.g();ok(e.parentNode===b,"player placed at same level as tag");ok(a.parentNode!==b,"tag removed from original place");d.m()});
test("should load a media controller",function(){var a=ib({da:"none",sc:[{src:"http://google.com",type:"video/mp4"},{src:"http://google.com",type:"video/webm"}]});ok(-1!==a.g().children[0].className.indexOf("vjs-tech"),"media controller loaded");a.m()});
test("should not play if firstplay event prevents default",function(){expect(1);var a=ib({preload:"none",autoplay:j,sources:[{src:"http://google.com",type:"video/mp4"},{src:"http://google.com",type:"video/webm"}]});a.e("firstplay",function(a){ok(f,"firstplay triggered");a.preventDefault()});a.e("play",function(){ok(j,"play triggered anyway")});a.play();a.m()});module("Setup");})();//@ sourceMappingURL=video.js.map
