import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

import type { Plugin } from 'rolldown';
import { rolldown } from 'rolldown';
import { describe, expect, it } from 'vite-plus/test';

import type { ResolvedStyleRule } from '../../styles/resolved';
import { toPosixPath } from '../../utils/path';
import {
  CANDIDATES_ALIAS,
  createCandidateManifest,
  parseCandidateManifest,
  renderCandidateManifest,
  resolveCandidateManifestPath,
  type StylePluginConfig,
  stylePlugin,
} from '../style';

const filename = resolve(import.meta.dirname, 'component.tsx');
const modulePath = resolve(import.meta.dirname, 'fixtures/button.styles.ts');
const moduleId = `${filename}?target=react`;
const designPath = resolve(import.meta.dirname, 'fixtures/design.css');
const designDependency = resolve(import.meta.dirname, 'fixtures/theme.css');

describe('renderCandidateManifest', () => {
  it('lists base and variant utilities once as Tailwind inline sources', () => {
    const button = { ...rule(['root'], 'media-button', ['grid', 'p-0']), variants: { compact: ['p-1', 'grid'] } };

    expect(renderCandidateManifest([button])).toBe(
      [
        '/* Generated by vjsc. Style module utilities for Tailwind source scanning. */',
        '@source inline("grid");',
        '@source inline("p-0");',
        '@source inline("p-1");',
        '',
      ].join('\n')
    );
  });
});

describe('createCandidateManifest', () => {
  it('lands parallel records as one well-formed manifest', async () => {
    const path = join(await mkdtemp(join(tmpdir(), 'vjsc-manifest-')), 'vjsc/candidates.css');
    const manifest = createCandidateManifest(path);
    const utilities = Array.from({ length: 24 }, (_, index) => `p-${index}`);

    await manifest.ensure();
    await Promise.all(
      utilities.map((utility, index) =>
        manifest.record({
          modules: new Map([
            [`module-${index}`, new Map([['root', rule(['root'], `media-${index}`, [utility, 'grid'])]])],
          ]),
          rules: [],
          watchFiles: [],
        })
      )
    );

    const content = await readFile(path, 'utf8');
    const stray = content
      .split('\n')
      .filter((line) => line && !line.startsWith('/*') && !/^@source inline\(".*"\);$/.test(line));

    expect(stray).toEqual([]);
    expect(parseCandidateManifest(content)).toEqual(expect.arrayContaining([...utilities, 'grid']));
  });
});

describe('resolveCandidateManifestPath', () => {
  it('places the manifest in the owning package cache directory', () => {
    const packageDir = resolve(import.meta.dirname, '../../..');

    expect(resolveCandidateManifestPath(import.meta.dirname)).toBe(
      resolve(packageDir, 'node_modules/.vite/vjsc/candidates.css')
    );
    expect(resolveCandidateManifestPath(packageDir, '.cache')).toBe(resolve(packageDir, '.cache/vjsc/candidates.css'));
  });
});

describe('stylePlugin', () => {
  it('aliases the default candidate manifest and re-includes it in the Vite watcher', () => {
    const plugin = stylePlugin({ mode: 'tailwind' }, {}, undefined, true) as Plugin & {
      config(config: { root?: string }): {
        resolve: { alias: Array<{ find: string; replacement: string }> };
        server: { watch: { ignored: string[] } };
      } | null;
    };
    const manifest = resolveCandidateManifestPath(import.meta.dirname);

    expect(plugin.config({ root: import.meta.dirname })).toEqual({
      resolve: { alias: [{ find: CANDIDATES_ALIAS, replacement: manifest }] },
      server: { watch: { ignored: [`!${toPosixPath(manifest)}`] } },
    });
  });

  it('keeps candidates from an earlier session until modules record again', async () => {
    const manifest = join(await mkdtemp(join(tmpdir(), 'vjsc-candidates-')), 'candidates.css');
    const plugin = stylePlugin({ mode: 'tailwind' }, {}, undefined, manifest);

    await writeFile(manifest, renderCandidateManifest([rule(['old'], 'media-old', ['persisted-class'])]));
    await transform(
      `import styles from './fixtures/utilities.styles'; export const root = <div className={styles.button} />;`,
      undefined,
      plugin
    );

    const content = await readFile(manifest, 'utf8');

    expect(parseCandidateManifest(content)).toEqual(['grid', 'p-0', 'persisted-class', 'shrink-0', 'size-4']);
  });

  it('writes a candidate manifest for every resolved style module', async () => {
    const manifest = join(await mkdtemp(join(tmpdir(), 'vjsc-candidates-')), 'candidates.css');
    const plugin = stylePlugin({ mode: 'tailwind' }, {}, undefined, manifest);

    await transform(
      `import styles from './fixtures/utilities.styles'; export const root = <div className={styles.button} />;`,
      undefined,
      plugin
    );

    const content = await readFile(manifest, 'utf8');

    expect(content).toContain('@source inline("grid");');
    expect(content).toContain('@source inline("size-4");');
  });

  it('rewrites style references with the Oxc AST and preserves expression source', async () => {
    const { source } = await transform(`
      import styles from './fixtures/utilities.styles';
      export function Example({ active }) {
        return <button className={[styles.button, active && styles.icon, 'hook']} />;
      }
    `);

    expect(source).not.toContain('utilities.styles');
    expect(source).toContain('className={["grid", "p-0", active && "size-4 shrink-0", \'hook\']}');
  });

  it('rewrites static style references outside JSX', async () => {
    const { source } = await transform(`
      import styles from './fixtures/utilities.styles';
      export const buttonClass = styles.button;
    `);

    expect(source).not.toContain('utilities.styles');
    expect(source).toContain('buttonClass = "grid p-0"');
  });

  it('preserves authored utility groups in direct JSX class values', async () => {
    const { source } = await transform(
      `import styles from './fixtures/utilities.styles'; export const root = <div className={styles.button} />;`
    );

    expect(source).toContain('className={["grid", "p-0"]}');
  });

  it('preserves semantic hooks without utilities in Tailwind output', async () => {
    const { source } = await transform(
      `import styles from './fixtures/hooks.styles'; export const root = <div className={styles.root} />;`,
      { mode: 'tailwind' }
    );

    expect(source).toContain('className={"video-controls"}');
  });

  it('combines normalized variants in selection order', async () => {
    const input = `
      import styles from './fixtures/button.styles';
      export const button = <button className={styles.root} />;
    `;
    const base = await transform(input, undefined, stylePlugin({ mode: 'tailwind' }));
    const selected = await transform(
      input,
      undefined,
      stylePlugin({ mode: 'tailwind', variants: ['compact', 'disabled'] })
    );

    expect(base.source).toContain('p-3');
    expect(base.source).not.toContain('pointer-events-none');
    expect(selected.source).toContain('p-1');
    expect(selected.source).not.toContain('p-3');
    expect(selected.source).toContain('pointer-events-none');
  });

  it.each(['css', 'tailwind'] as const)('preserves custom font sizes with variants in %s output', async (mode) => {
    const plugin = stylePlugin({ mode, variants: ['minimal'], stylesheet: { input: designPath } });
    const { source } = await transform(
      `import styles from './fixtures/title.styles'; export const title = <div className={styles.root} />;`,
      undefined,
      plugin
    );

    if (mode === 'tailwind') {
      expect(source).toContain('text-fixture-title');
      expect(source).toContain('text-fixture-foreground');
      expect(source).toContain('font-normal');
      expect(source).not.toContain('font-medium');
    } else {
      const id = virtualCssIds(source)[0];
      if (!id) throw new Error('Expected a generated stylesheet.');

      const css = await loadPlugin(plugin, id);

      expect(css).toContain('font-size: 1.5rem');
      expect(css).toContain('font-weight: 400');
      expect(css).toContain('color:');
    }
  });

  it('forwards multiple variants to generated CSS', async () => {
    const styles = stylePlugin({
      mode: 'css',
      variants: ['compact', 'disabled'],
      stylesheet: { input: designPath },
    });
    const { source } = await transform(
      `
        import styles from './fixtures/button.styles';
        export const button = <button className={styles.root} />;
      `,
      undefined,
      styles
    );
    const id = virtualCssIds(source)[0];
    if (!id) throw new Error('Expected a generated semantic stylesheet.');

    const css = await loadPlugin(styles, id);

    expect(css).toContain('padding: .25rem');
    expect(css).not.toContain('padding: .75rem');
    expect(css).toContain('pointer-events: none');
  });

  it('rejects non-static style binding usage', async () => {
    const source = `import styles from './fixtures/utilities.styles'; export const value = styles;`;

    await expect(transform(source)).rejects.toMatchObject({
      errors: [
        {
          message: expect.stringContaining('must use static references'),
          pos: source.lastIndexOf('styles'),
        },
      ],
    });
  });

  it('tracks imported design-system files and preserves directives', async () => {
    const { source, watchFiles } = await transform(
      `
        'use client';
        import styles from './fixtures/utilities.styles';
        export const button = <button className={styles.button} />;
      `,
      { mode: 'css', stylesheet: { input: designPath } }
    );

    const directive = source.indexOf(`'use client'`);
    const cssImport = source.indexOf('virtual:vjsc/css');

    expect(watchFiles).toContain(designPath);
    expect(watchFiles).toContain(designDependency);
    expect(directive).toBeGreaterThanOrEqual(0);
    expect(cssImport).toBeGreaterThanOrEqual(0);
    expect(directive).toBeLessThan(cssImport);
  });

  it('imports runtime base CSS before generated semantic styles', async () => {
    const { source } = await transform(
      `
        import styles from './fixtures/utilities.styles';
        export const button = <button className={styles.button} />;
      `,
      {
        mode: 'css',
        stylesheet: { input: designPath, base: designDependency },
      }
    );

    const base = source.indexOf('/base.css');
    const semantic = source.indexOf('/buttons.css');

    expect(base).toBeGreaterThanOrEqual(0);
    expect(semantic).toBeGreaterThan(base);
  });

  it('releases stale hashed CSS modules when an owner is recompiled', async () => {
    let scope = '.first';
    const styles = stylePlugin(() => ({
      mode: 'css',
      stylesheet: { input: designPath, scope },
    }));
    const input = `
      import styles from './fixtures/utilities.styles';
      export const button = <button className={styles.button} />;
    `;

    const first = await transform(input, undefined, styles);

    scope = '.second';
    const second = await transform(input, undefined, styles);
    const firstId = virtualCssIds(first.source)[0];
    const secondId = virtualCssIds(second.source)[0];

    expect(firstId).toBeDefined();
    expect(secondId).toBeDefined();
    expect(secondId).not.toBe(firstId);
    expect(await resolvePluginId(styles, firstId!)).toBeNull();
    expect(await resolvePluginId(styles, secondId!)).toBe(`\0${secondId}`);
  });

  it('warns once when authored and compiled checks find the same complex selector', async () => {
    const styles = stylePlugin({
      mode: 'css',
      stylesheet: { input: designPath },
    });
    const { warnings } = await transform(
      `import styles from './fixtures/complex.styles'; export const root = <div className={styles.root} />;`,
      undefined,
      styles
    );

    expect(warnings).toHaveLength(1);
    expect(warnings[0]).toContain('[VJSC_STYLE_COMPLEX_SELECTOR]');
    expect(warnings[0]).toContain('`[&_img]:block`, `[&_video]:block`');
    expect(warnings[0]).toContain('Reason:');
    expect(warnings[0]).toContain('Recommendation:');
  });

  it('promotes or silences complex-selector warnings', async () => {
    const input = `import styles from './fixtures/complex.styles'; export const root = <div className={styles.root} />;`;

    await expect(
      transform(input, undefined, stylePlugin({ mode: 'tailwind' }, { complexSelectors: 'error' }))
    ).rejects.toThrow('[VJSC_STYLE_COMPLEX_SELECTOR]');

    const { warnings } = await transform(
      input,
      undefined,
      stylePlugin({ mode: 'tailwind' }, { complexSelectors: 'off' })
    );

    expect(warnings).toEqual([]);
  });

  it('keeps isolation errors active when complex-selector warnings are off', async () => {
    const input = `import styles from './fixtures/peer.styles'; export const root = <div className={styles.root} />;`;

    await expect(
      transform(input, undefined, stylePlugin({ mode: 'tailwind' }, { complexSelectors: 'off' }))
    ).rejects.toThrow('[VJSC_STYLE_PEER_RELATIONSHIP]');
  });
});

async function transform(
  source: string,
  config: StylePluginConfig = { mode: 'tailwind' },
  styles: Plugin = stylePlugin(config)
): Promise<{
  readonly source: string;
  readonly warnings: readonly string[];
  readonly watchFiles: readonly string[];
}> {
  let output: string | undefined;
  const warnings: string[] = [];
  const inspect: Plugin = {
    name: 'fixture:inspect',
    buildEnd() {
      output = this.getModuleInfo(moduleId)?.code ?? undefined;
    },
  };
  const bundle = await rolldown({
    input: 'fixture',
    experimental: { nativeMagicString: true },
    external: /^virtual:vjsc\/css\//,
    transform: { jsx: 'preserve' },
    plugins: [fixturePlugin(source), styles, inspect],
    onLog(level, log) {
      if (level === 'warn') warnings.push(log.message);
    },
  });

  await bundle.generate({ format: 'es' });

  if (output === undefined) throw new Error('Fixture build did not retain editable source.');

  return {
    source: output,
    warnings,
    watchFiles: await bundle.watchFiles,
  };
}

function virtualCssIds(source: string): string[] {
  return [...source.matchAll(/["'](virtual:vjsc\/css\/[^"']+)["']/g)].map((match) => match[1]!);
}

async function resolvePluginId(plugin: Plugin, id: string): Promise<unknown> {
  const hook = plugin.resolveId;
  if (!hook) return null;

  const handler = typeof hook === 'function' ? hook : hook.handler;

  return (handler as (id: string) => unknown)(id);
}

async function loadPlugin(plugin: Plugin, id: string): Promise<string> {
  const resolved = await resolvePluginId(plugin, id);
  if (typeof resolved !== 'string') throw new Error(`Could not resolve ${id}.`);

  const hook = plugin.load;
  if (!hook) throw new Error('Expected the style plugin to provide a load hook.');

  const handler = typeof hook === 'function' ? hook : hook.handler;
  const result = await (handler as (id: string) => unknown)(resolved);
  if (typeof result !== 'string') throw new Error(`Could not load ${id}.`);

  return result;
}

function fixturePlugin(source: string): Plugin {
  return {
    name: 'fixture:module',
    resolveId(id) {
      return id === 'fixture' ? moduleId : null;
    },
    load(id) {
      return id === moduleId ? { code: source, moduleType: 'tsx' } : null;
    },
  };
}

function rule(tokenPath: readonly string[], className: string, utilities: readonly string[]): ResolvedStyleRule {
  return {
    modulePath,
    tokenPath,
    className,
    file: 'buttons.css',
    layer: 'videojs.components',
    scopeRoot: false,
    shadowHost: false,
    utilityGroups: utilities,
    utilities,
    variantGroups: {},
    variants: {},
  };
}
