#!/usr/bin/env bash
# Commit the rewritten changelog on a bot-owned branch, push it, and open a PR
# against main unless one for that branch is already open.
#
# Usage: changelog-prose-open-pr.sh [VERSION] [RELEASE_URL]
#
#   VERSION            Release version, e.g. 10.0.0 (or env VERSION)
#   RELEASE_URL        GitHub release page linked from the PR body (or env RELEASE_URL)
#   CONTEXT_DIR        Scratch directory for the PR body (env; default .prose-context)
#   GITHUB_REPOSITORY  owner/name the PR is opened on (env; default videojs/video.js)
#   GH_TOKEN           `gh` must be authenticated; git push uses the checkout's origin
#
# Runs from the repository root regardless of the caller's cwd. The commit is
# authored as github-actions[bot] without touching the checkout's git config.
set -euo pipefail

VERSION="${1:-${VERSION:-}}"
RELEASE_URL="${2:-${RELEASE_URL:-}}"
CONTEXT_DIR="${CONTEXT_DIR:-.prose-context}"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-videojs/video.js}"

if [ -z "$VERSION" ] || [ -z "$RELEASE_URL" ]; then
  echo "Usage: $(basename "$0") VERSION RELEASE_URL" >&2
  echo "  VERSION      release version, e.g. 10.0.0 (or env VERSION)" >&2
  echo "  RELEASE_URL  release page URL for the PR body (or env RELEASE_URL)" >&2
  echo "  Requires an authenticated gh (GH_TOKEN) and push access to origin." >&2
  exit 2
fi

cd "$(dirname "$0")/../.."

FILE="site/src/content/changelog/${VERSION}.mdx"
BRANCH="docs/changelog-prose-${VERSION}"
TITLE="docs(site): add changelog prose for ${VERSION}"
# The Cherry-pick to site/v10 workflow ships PRs with this label to videojs.org
# when they merge. Prose follows a published release, so production already
# runs that version.
LABEL="cherry-pick:site"

git switch -c "$BRANCH"
git add -- "$FILE"
# commitlint's scope-enum has no `changelog` scope, so use `site`.
git -c user.name="github-actions[bot]" \
    -c user.email="github-actions[bot]@users.noreply.github.com" \
    commit -m "$TITLE"

# A re-dispatch for the same tag regenerates the prose, so replace
# whatever an earlier run pushed. The branch is bot-owned, and the
# lease still rejects the push if it moved since this fetch.
git fetch origin "+refs/heads/${BRANCH}:refs/remotes/origin/${BRANCH}" \
  || echo "No existing ${BRANCH} on origin"
git push --force-with-lease="refs/heads/${BRANCH}" origin "HEAD:refs/heads/${BRANCH}"

EXISTING=$(gh pr list --repo "$GITHUB_REPOSITORY" --head "$BRANCH" --base main --state open --json number --jq '.[0].number // empty')
if [ -n "$EXISTING" ]; then
  echo "Updated existing PR #${EXISTING} for ${BRANCH}"
  exit 0
fi

mkdir -p "$CONTEXT_DIR"
cat > "$CONTEXT_DIR/pr-body.md" <<EOF
Rewrites the raw changelog for \`${VERSION}\` into narrative prose and fills in its \`description\`.

Release: ${RELEASE_URL}

Generated by the Changelog Prose workflow. Review the story against the release before merging. The \`${LABEL}\` label ships it to videojs.org on merge; remove the label to hold it until the next release.
EOF
gh pr create \
  --repo "$GITHUB_REPOSITORY" \
  --base main \
  --head "$BRANCH" \
  --title "$TITLE" \
  --label "$LABEL" \
  --body-file "$CONTEXT_DIR/pr-body.md"
