export default {
  extends: ['@commitlint/config-conventional'],
  formatter: '@commitlint/format',
  ignores: [
    /** @param {string} message */
    (message) => {
      const lower = message.toLowerCase().trim();

      return ['wip'].some((word) => lower.startsWith(word));
    },
  ],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'build',
        'cd',
        'cdn',
        'ci',
        'claude',
        'cli',
        'vjsc',
        'core',
        'design',
        'element',
        'docs',
        'html',
        'installation',
        'i18n',
        'icons',
        'jsx',
        'media',
        'mux',
        'cloudflare-video',
        'playerjs-video',
        'spotify-audio',
        'tiktok-video',
        'twitch-video',
        'youtube-video',
        'native-hls-video',
        'dash-video',
        'google-cast',
        'hlsjs-video',
        'mux-audio',
        'mux-data',
        'mux-video',
        'shaka-video',
        'vimeo-video',
        'wistia-video',
        'packages',
        'plan',
        'react-native',
        'react',
        'rfc',
        'root',
        'sandbox',
        'site',
        'skin',
        'spf',
        'store',
        'test',
        'utils',
        'video.js',
      ],
    ],
  },
};
