import { globSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { defineConfig } from 'vite-plus';
import type { UserConfig as PackUserConfig } from 'vite-plus/pack';

import { baseConfig, inlineCssConfig } from '../../build/pack.ts';
import { copyCssPlugin } from '../../build/plugins/copy-css-plugin.ts';
import type { BuildPlugin } from '../../build/plugins/types.ts';
import { cachedTaskInputs, workspaceTaskDependencies } from '../../build/task.ts';
import { LOCALES, localeAliases } from '../core/src/core/i18n/locales.ts';
import { cdnHtmlEntries } from './scripts/cdn-html-entries.ts';
import { cdnI18nExternalPlugin } from './scripts/cdn-i18n-external-plugin.ts';

type CdnBuildMode = 'dev' | 'prod';

const packageDir = dirname(fileURLToPath(import.meta.url));
// The bundles are built from `@videojs/html`'s published output, resolved the same way a consumer would, so the CDN
// never reaches into another package's sources. Its stylesheets are copied from that output, and its media, extension,
// and UI bundles are listed from it.
const htmlDistDir = resolve(
  dirname(createRequire(import.meta.url).resolve('@videojs/html/package.json')),
  'dist/default'
);
// Generated skin registrations register elements as a side effect and export nothing.
const generatedSkinRegistration = /\/internal\/skins\/.+\/register\.[cm]?[jt]s$/;
const localeTags = [...LOCALES, ...localeAliases(LOCALES)];

const cdnPresets = [
  'video',
  'video-player',
  'video-neutral',
  'video-compat',
  'video-scaffold',
  'live-video',
  'live-video-player',
  'live-video-neutral',
  'live-video-compat',
  'live-video-scaffold',
  'audio',
  'audio-player',
  'audio-neutral',
  'audio-compat',
  'audio-scaffold',
  'live-audio',
  'live-audio-player',
  'live-audio-neutral',
  'live-audio-compat',
  'live-audio-scaffold',
  'background',
];

// Bare `@videojs/html/...` specifiers as entries: rolldown resolves them like any import, so the dev build follows the
// `development` condition to html's dev output and the prod build follows `default`.
const cdnHtmlDefinitionEntries = cdnHtmlEntries(resolve(htmlDistDir, 'define'));

const cdnLocaleEntries = localeTags.map((tag) => ({
  src: `src/locales/${tag}.ts`,
  name: `locales/${tag}`,
}));

export const entries = [
  { src: 'src/i18n.ts', name: 'i18n' },
  ...cdnLocaleEntries,
  ...cdnPresets.map((name) => ({ src: `src/${name}.ts`, name })),
  ...cdnHtmlDefinitionEntries,
];

function cdnStylesheetName(file: string): string | null {
  const match = /^define\/(?:([\w-]+)\/)?([\w-]+)\.css$/.exec(file);
  if (!match) return null;

  const [, preset, name] = match;
  if (!preset) return `${name}.css`;

  if (preset === 'background') return name === 'skin' ? 'background.css' : null;

  const suffix =
    name === 'skin'
      ? ''
      : name === 'neutral-skin'
        ? '-neutral'
        : name === 'compat-skin'
          ? '-compat'
          : name === 'scaffold-skin'
            ? '-scaffold'
            : null;
  if (suffix === null) return null;

  return `${preset}${suffix}.css`;
}

function cleanCdnOutputPlugin(): BuildPlugin {
  return {
    name: 'clean-cdn-output',
    buildStart() {
      // The entry list is read from html's output when this config loads; an empty list means that output was missing.
      if (cdnHtmlDefinitionEntries.length === 0) {
        throw new Error(`No @videojs/html definitions found under ${htmlDistDir}. Build @videojs/html first.`);
      }

      for (const dir of ['chunks', 'extensions', 'locales', 'media', 'ui']) {
        rmSync(resolve(packageDir, dir), { recursive: true, force: true });
      }

      for (const file of globSync('*.{css,js,js.map}', { cwd: packageDir })) {
        rmSync(resolve(packageDir, file), { force: true });
      }

      for (const file of globSync('*.d.ts', { cwd: packageDir })) {
        rmSync(resolve(packageDir, file), { force: true });
      }
    },
  };
}

/**
 * Every bundle except `i18n` registers elements as a side effect and exports nothing, so an empty module is its true
 * type. `i18n` is the one entry consumers import by name; its declarations are generated by the `cdn-i18n-types` pack.
 */
function dtsStubsPlugin(outDir: string): BuildPlugin {
  return {
    name: 'cdn-dts-stubs',
    writeBundle(_options, bundle) {
      for (const file of Object.keys(bundle)) {
        if (!file.endsWith('.dev.js') || file === 'i18n.dev.js') continue;

        writeFileSync(resolve(outDir, file.replace('.dev.js', '.dev.d.ts')), 'export {};\n');
      }
    },
  };
}

/** Comment at the top of every CDN entry, so anything that fetches the script finds its way to the docs. */
const CDN_BANNER = '/*! Video.js | https://videojs.org/help */';

const cdnPackConfigs: PackUserConfig[] = [];

for (const mode of ['dev', 'prod'] satisfies CdnBuildMode[]) {
  const isProd = mode === 'prod';
  const entry = Object.fromEntries(entries.map(({ src, name }) => [isProd ? name : `${name}.dev`, src]));

  cdnPackConfigs.push({
    ...baseConfig,
    css: inlineCssConfig,
    name: 'cdn',
    entry,
    platform: 'browser',
    format: 'es',
    target: 'es2022',
    sourcemap: true,
    clean: false,
    dts: false,
    minify: isProd,
    // Only the files a page loads directly carry the banner; shared chunks stay bare.
    outputOptions: { banner: (chunk) => (chunk.isEntry ? CDN_BANNER : '') },
    deps: {
      alwaysBundle: [/.*/],
      onlyBundle: false,
    },
    treeshake: {
      moduleSideEffects: [
        { test: generatedSkinRegistration, sideEffects: true },
        { test: /\/define\//, sideEffects: true },
        { test: /\/icons\/(?:dist\/)?element\//, sideEffects: true },
      ],
    },
    outDir: packageDir,
    define: { __DEV__: isProd ? 'false' : 'true' },
    plugins: [
      ...(!isProd ? [cleanCdnOutputPlugin()] : []),
      cdnI18nExternalPlugin({ prod: isProd }),
      ...(isProd
        ? [
            // html's build already resolved every `@import`, so the sheets are copied as-is and only minified.
            copyCssPlugin({
              rootDir: htmlDistDir,
              pattern: 'define/**/*.css',
              outDir: packageDir,
              rename: cdnStylesheetName,
              inline: false,
              minify: true,
            }),
          ]
        : [dtsStubsPlugin(packageDir)]),
    ],
    inputOptions: {
      ...baseConfig.inputOptions,
      onwarn(warning, defaultHandler) {
        if (warning.code === 'COMMONJS_VARIABLE_IN_ESM') return;

        defaultHandler(warning);
      },
      ...(!isProd && {
        resolve: { conditionNames: ['development', 'import', 'browser', 'default'] },
      }),
    },
  });
}

// Declarations for the `i18n` entry, bundled from `@videojs/core/i18n` the same way its JavaScript is, so
// `@videojs/cdn/i18n` types resolve without installing any other package.
cdnPackConfigs.push({
  ...baseConfig,
  name: 'cdn',
  entry: { 'i18n.dev': 'src/i18n.ts' },
  platform: 'browser',
  format: 'es',
  clean: false,
  outDir: packageDir,
  dts: { emitDtsOnly: true, generator: 'tsgo', tsconfig: 'tsconfig.dts.json' },
  deps: { dts: { alwaysBundle: [/^@videojs\//] } },
});

export default defineConfig({
  define: {
    __DEV__: 'true',
  },
  run: {
    tasks: {
      'build:cdn': {
        command: 'node --import tsx ./scripts/build-cdn-locales.ts && vp pack --filter cdn',
        dependsOn: workspaceTaskDependencies(),
        cache: {
          input: [
            ...cachedTaskInputs,
            '!src/locales/',
            '!src/locales/**',
            '!*.css',
            '!*.d.ts',
            '!*.js',
            '!*.js.map',
            '!chunks/',
            '!chunks/**',
            '!extensions/',
            '!extensions/**',
            '!locales/',
            '!locales/**',
            '!media/',
            '!media/**',
            '!ui/',
            '!ui/**',
          ],
          output: [
            'src/locales/**',
            '*.css',
            '*.d.ts',
            '*.js',
            '*.js.map',
            'chunks/**',
            'extensions/**',
            'locales/**',
            'media/**',
            'ui/**',
          ],
        },
      },
      'test:ci': {
        command: 'pnpm test',
        cache: false,
        dependsOn: workspaceTaskDependencies(),
      },
    },
  },
  test: {
    // Vitest v4 compatibility: preserve mock call history.
    // Remove after tests no longer rely on calls from setup or earlier tests.
    // https://viteplus.dev/guide/vitest-v5#remove-unneeded-compatibility-settings
    // https://vitest.dev/guide/migration/#clearmocks-is-enabled-by-default
    clearMocks: false,
    environment: 'node',
  },
  pack: cdnPackConfigs,
});
