import { fileURLToPath } from 'node:url';

import { file, glob } from 'astro/loaders';
import { z } from 'astro/zod';
import { defineCollection, reference } from 'astro:content';

import { ComponentReferenceSchema } from './types/component-reference';
import { DOC_STABILITIES, DOC_TYPES, getDocTypeFromId, SUPPORTED_FRAMEWORKS } from './types/docs';
import { FeatureReferenceSchema } from './types/feature-reference';
import { MediaReferenceSchema } from './types/media-reference';
import { PresetReferenceSchema } from './types/preset-reference';
import { UtilReferenceSchema } from './types/util-reference';
import { createGitService } from './utils/gitService';
import { globWithParser } from './utils/globWithParser';

// One history walk of the content directory serves every entry. Lookups use the absolute `filePath` the loader
// passes to `parseData`, so they do not depend on the working directory Astro runs from or on `generateId` rewrites.
const CONTENT_ROOT = fileURLToPath(new URL('./content/', import.meta.url));
const gitService = createGitService(CONTENT_ROOT);

/**
 * Extract date from filename in format: YYYY-MM-DD-slug.mdx Throws an error if the filename doesn't match the expected
 * pattern
 */
export function extractDateFromFilename(id: string): Date {
  const match = id.match(/^(\d{4})-(\d{2})-(\d{2})-/);
  if (!match) throw new Error(`Filename "${id}" must follow format: YYYY-MM-DD-slug.mdx`);

  const [, year, month, day] = match;

  return new Date(`${year}-${month}-${day}`);
}

const blog = defineCollection({
  // Load MDX files in the `src/content/blog/` directory.
  loader: globWithParser({
    base: './src/content/blog',
    pattern: '**/*.mdx',
    generateId: ({ entry }) => {
      // Remove date prefix and extension from slug (e.g., "2022-07-08-first-post.mdx" -> "first-post")
      return entry.replace(/^\d{4}-\d{2}-\d{2}-/, '').replace(/\.mdx$/, '');
    },
    parser: async (entry, originalEntry) => {
      // Extract pubDate from original filename (before date prefix was removed)
      const pubDate = extractDateFromFilename(originalEntry);

      // Get updatedDate from git history (last modification date)
      const updatedDate = entry.filePath ? await gitService.getLastModifiedDate(entry.filePath) : null;

      // Return transformed entry with added fields
      return {
        ...entry,
        data: {
          ...entry.data,
          pubDate,
          ...(updatedDate && updatedDate.getTime() !== pubDate.getTime() ? { updatedDate } : {}),
        },
      };
    },
  }),
  // Type-check frontmatter using a schema
  schema: ({ image }) =>
    z.object({
      title: z.string(),
      description: z.string(),
      pubDate: z.date(),
      updatedDate: z.coerce.date().optional(),
      authors: z.array(reference('authors')),
      canonical: z.url().optional(),
      devOnly: z.boolean().optional(), // only visible in development mode
      ogTitle: z.string().optional(),
      ogImage: image().or(z.url()).optional(),
      twitterImage: image().or(z.url()).optional(),
    }),
});

const docs = defineCollection({
  loader: globWithParser({
    base: './src/content/docs',
    pattern: '**/*.mdx',
    parser: async (entry) => {
      // Get updatedDate from git history
      const updatedDate = entry.filePath ? await gitService.getLastModifiedDate(entry.filePath) : null;

      // The folder decides the Diátaxis type; it overrides anything an author writes in frontmatter.
      return {
        ...entry,
        data: {
          ...entry.data,
          type: getDocTypeFromId(entry.id),
          ...(updatedDate ? { updatedDate } : {}),
        },
      };
    },
  }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    type: z.enum(DOC_TYPES),
    updatedDate: z.coerce.date().optional(),
    ogTitle: z.string().optional(),
    stability: z.enum(DOC_STABILITIES).optional(),
    frameworkTitle: z.partialRecord(z.enum(SUPPORTED_FRAMEWORKS as [string, ...string[]]), z.string()).optional(),
    // Exports a reference page documents that its subject, code headings, and Exports tables don't name: export names,
    // exact `@videojs/...` entry points (every export), or `*` module patterns (each default export). Read by
    // `scripts/check-api-stability.ts`, which fails on entries that match nothing.
    apis: z.array(z.string()).optional(),
  }),
});

// Release notes generated by the release workflow (raw git-cliff bullets),
// then rewritten into prose by the changelog-prose workflow. MDX lets the
// changelog use the same typography component mapping as the blog.
const changelog = defineCollection({
  loader: glob({
    base: './src/content/changelog',
    pattern: '*.mdx',
    generateId: ({ entry }) => entry.replace(/\.mdx$/, ''),
  }),
  schema: z.object({
    description: z.string(),
    date: z.coerce.date(),
    version: z.string(),
    prerelease: z.boolean(),
    breaking: z.boolean(),
    compareUrl: z.url(),
  }),
});

const authors = defineCollection({
  loader: file('./src/content/authors.json'),
  schema: z.object({
    name: z.string(),
    shortName: z.string(),
    bio: z.string().optional(),
    avatar: z.string().optional(),
    socialLinks: z
      .object({
        x: z.string().optional(),
        bluesky: z.string().optional(),
        mastodon: z.string().optional(),
        github: z.string().optional(),
        linkedin: z.string().optional(),
        website: z.string().optional(),
      })
      .optional(),
  }),
});

const componentReference = defineCollection({
  loader: glob({
    pattern: '*.json',
    base: './src/content/generated-component-reference',
  }),
  schema: ComponentReferenceSchema,
});

const utilReference = defineCollection({
  loader: glob({
    pattern: '*.json',
    base: './src/content/generated-util-reference',
  }),
  schema: UtilReferenceSchema,
});

const featureReference = defineCollection({
  loader: glob({
    pattern: '*.json',
    base: './src/content/generated-feature-reference',
  }),
  schema: FeatureReferenceSchema,
});

const mediaReference = defineCollection({
  loader: glob({
    pattern: '*.json',
    base: './src/content/generated-media-reference',
  }),
  schema: MediaReferenceSchema,
});

const presetReference = defineCollection({
  loader: glob({
    pattern: '*.json',
    base: './src/content/generated-preset-reference',
  }),
  schema: PresetReferenceSchema,
});

export const collections = {
  blog,
  docs,
  changelog,
  authors,
  componentReference,
  utilReference,
  featureReference,
  mediaReference,
  presetReference,
};
