import { RuleTester } from "vite-plus/lint/plugins-dev";
import { describe, it } from "vite-plus/test";

import { paddingLineBetweenStatementsRule } from "../padding-line-between-statements.ts";

RuleTester.describe = describe;
RuleTester.it = it;

const ruleTester = new RuleTester({
	languageOptions: { parserOptions: { lang: "ts" } },
});

const crlf = (source: string) => source.replaceAll("\n", "\r\n");

ruleTester.run("padding-line-between-statements", paddingLineBetweenStatementsRule, {
	valid: [
		{
			name: "declaration-backed guard clauses",
			code: `function run(locale: string) {
  const target = resolveTarget(locale);
  if (!target) return {};

  const { value } = readTarget(target);
  /* Missing values cannot be normalized.

     Exit before entering the loop. */
  if (!value) throw new Error("Missing value");

  for (const item of value) {
    const normalized = normalize(item);
    if (!normalized) continue;

    use(normalized);
  }

  while (true) {
    const next = readNext();
    if (!next) break;

    use(next);
  }

  const labeled = readLabeled();
  guard: if (!labeled) return;
}`,
		},
		{
			name: "non-collapsible guards remain separate control-flow paragraphs",
			code: `function run() {
  const commented = readCommented();

  if (!commented) {
    // Preserve the reason for returning.
    return;
  }

  const multilineExit = readMultiline();

  if (!multilineExit) {
    return createFallback(
      multilineExit
    );
  }

  const multiStatement = readMultiple();

  if (!multiStatement) {
    recordFailure();
    return;
  }

  const multilineCondition = readCondition();

  if (
    !multilineCondition
  ) return;
}`,
		},
		{
			name: "logical declaration groups",
			code: `function run() {
  const first = createFirst();
  const second = createSecond();

  const unrelated = createUnrelated();

  if (unrelated) {
    use(first, second);
  }

  return unrelated;
}`,
		},
		{
			name: "a later declaration may begin after an expression",
			code: `function run() {
  prepare();
  const result = finish();

  return result;
}`,
		},
		{
			name: "generated source",
			code: `/** Generated by example. */
function run() {
  const result = prepare();
  if (result) return result;
  return null;
}`,
		},
	],
	invalid: [
		{
			name: "braced return guard",
			code: `function run() {
  const result = prepare();

  if (!result) {
    return;
  }
}`,
			output: `function run() {
  const result = prepare();
  if (!result) return;
}`,
			errors: [{ messageId: "collapsibleGuard", line: 4 }],
		},
		{
			name: "braced throw guard without padding",
			code: `function run() {
  const result = prepare();
  if (!result) {
    throw new Error("Missing result");
  }
}`,
			output: `function run() {
  const result = prepare();
  if (!result) throw new Error("Missing result");
}`,
			errors: [{ messageId: "collapsibleGuard", line: 3 }],
		},
		{
			name: "braced continue guard",
			code: `function run(items: string[]) {
  for (const item of items) {
    const normalized = normalize(item);

    if (!normalized) {
      continue;
    }

    use(normalized);
  }
}`,
			output: `function run(items: string[]) {
  for (const item of items) {
    const normalized = normalize(item);
    if (!normalized) continue;

    use(normalized);
  }
}`,
			errors: [{ messageId: "collapsibleGuard", line: 5 }],
		},
		{
			name: "braced break guard",
			code: `function run() {
  while (true) {
    const next = readNext();

    if (!next) {
      break;
    }

    use(next);
  }
}`,
			output: `function run() {
  while (true) {
    const next = readNext();
    if (!next) break;

    use(next);
  }
}`,
			errors: [{ messageId: "collapsibleGuard", line: 5 }],
		},
		{
			name: "commented braced guard keeps its block and gains padding",
			code: `function run() {
  const result = prepare();
  if (!result) {
    // Keep this explanation attached to the return.
    return;
  }
}`,
			output: `function run() {
  const result = prepare();

  if (!result) {
    // Keep this explanation attached to the return.
    return;
  }
}`,
			errors: [{ messageId: "expectedBlankLine", line: 3 }],
		},
		{
			name: "multiline unbraced guard gains padding",
			code: `function run() {
  const result = prepare();
  if (
    !result
  ) return;
}`,
			output: `function run() {
  const result = prepare();

  if (
    !result
  ) return;
}`,
			errors: [{ messageId: "expectedBlankLine", line: 3 }],
		},
		{
			name: "multiline labeled guard gains padding",
			code: `function run() {
  const result = prepare();
  guard:
  if (!result) return;
}`,
			output: `function run() {
  const result = prepare();

  guard:
  if (!result) return;
}`,
			errors: [{ messageId: "expectedBlankLine", line: 3 }],
		},
		{
			name: "CRLF blank lines between declarations and their guards",
			code: crlf(`function run() {
  const result = prepare();

  if (!result) return;
}`),
			output: crlf(`function run() {
  const result = prepare();
  if (!result) return;
}`),
			errors: [{ messageId: "unexpectedBlankLine", line: 4 }],
		},
		{
			name: "blank lines between declarations and their guards",
			code: `function run(locale: string) {
  const target = resolveTarget(locale);

  if (!target) return {};

  const cached = cache.get(target);

  // Cached results can return immediately.

  if (cached) return cached;
}`,
			output: `function run(locale: string) {
  const target = resolveTarget(locale);
  if (!target) return {};

  const cached = cache.get(target);
  // Cached results can return immediately.
  if (cached) return cached;
}`,
			errors: [
				{ messageId: "unexpectedBlankLine", line: 4 },
				{ messageId: "unexpectedBlankLine", line: 10 },
			],
		},
		{
			name: "an unrelated guard remains a separate paragraph",
			code: `function run() {
  const result = prepare();
  if (!systemReady) return;

  use(result);
}`,
			output: `function run() {
  const result = prepare();

  if (!systemReady) return;

  use(result);
}`,
			errors: [{ messageId: "expectedBlankLine", line: 3 }],
		},
		{
			name: "a shadowed binding does not back a guard",
			code: `function run() {
  const result = prepare();
  if ([null].some((result) => !result)) return;

  use(result);
}`,
			output: `function run() {
  const result = prepare();

  if ([null].some((result) => !result)) return;

  use(result);
}`,
			errors: [{ messageId: "expectedBlankLine", line: 3 }],
		},
		{
			name: "declaration group before a return",
			code: `function run() {
  const result = prepare();
  return result;
}`,
			output: `function run() {
  const result = prepare();

  return result;
}`,
			errors: [{ messageId: "expectedBlankLine", line: 3 }],
		},
		{
			name: "control flow between adjacent statements",
			code: `function run() {
  prepare();
  if (ready) {
    use();
  }
  finish();
}`,
			output: `function run() {
  prepare();

  if (ready) {
    use();
  }

  finish();
}`,
			errors: [
				{ messageId: "expectedBlankLine", line: 3 },
				{ messageId: "expectedBlankLine", line: 6 },
			],
		},
		{
			name: "leading comment stays with control flow",
			code: `function run() {
  const result = prepare();
  // Stop when preparation fails.
  if (!ready) return;
}`,
			output: `function run() {
  const result = prepare();

  // Stop when preparation fails.
  if (!ready) return;
}`,
			errors: [{ messageId: "expectedBlankLine", line: 4 }],
		},
		{
			name: "blank lines inside block comments do not count",
			code: `function run() {
  const result = prepare();
  /* Preparation and validation are separate phases.

     Validation starts here. */
  if (result) use(result);
}`,
			output: `function run() {
  const result = prepare();

  /* Preparation and validation are separate phases.

     Validation starts here. */
  if (result) use(result);
}`,
			errors: [{ messageId: "expectedBlankLine", line: 6 }],
		},
		{
			name: "labeled control flow",
			code: `function run(items: string[]) {
  prepare();
  outer: for (const item of items) {
    if (item) break outer;
  }
  finish();
}`,
			output: `function run(items: string[]) {
  prepare();

  outer: for (const item of items) {
    if (item) break outer;
  }

  finish();
}`,
			errors: [
				{ messageId: "expectedBlankLine", line: 3 },
				{ messageId: "expectedBlankLine", line: 6 },
			],
		},
		{
			name: "statements on the same line",
			code: "function run() { const result = prepare(); if (result) return result; return null; }",
			output:
				"function run() { const result = prepare(); if (result) return result;\n\n return null; }",
			errors: [{ messageId: "expectedBlankLine", line: 1 }],
		},
	],
});
