/**
 * Renders the model as Markdown pages, one per public entry, plus a README index. Pages hold only what the model read
 * from the sources; a symbol without JSDoc is marked "No description." and nothing more.
 */
import { dirname, relative } from 'node:path';

import ts from 'typescript';

import type { BehaviorInfo, ConfigRow, DocBlock, EngineInfo, FeatureInfo, Model, SlotRow, TypeField } from './model';
import {
  declarationSignature,
  declaringFile,
  docOf,
  exportKind,
  firstSentence,
  moduleExports,
  resolveAlias,
} from './model';
import type { EntryPoint, ReferenceProgram } from './program';

export const GENERATED_NOTICE =
  '<!-- Generated by `pnpm -F @videojs/spf docs:reference`. Do not edit by hand; edit the JSDoc in the source. -->';

const NO_DESCRIPTION = 'No description.';
const LONG_CELL = 200;
const CORE_MODULE_PREFIX = './core/composition/';

/** Pages keyed by their path under the reference root. */
export type Pages = Map<string, string>;

// ── Markdown helpers ─────────────────────────────────────────────────────────

/** GitHub's heading anchor for a plain-text heading. */
function anchor(heading: string): string {
  return heading
    .toLowerCase()
    .replace(/[^\w\- ]/g, '')
    .replace(/ /g, '-');
}

function link(fromPage: string, toPage: string, label: string, fragment = ''): string {
  const path = relative(dirname(fromPage), toPage) || '.';

  return `[${label}](${path}${fragment ? `#${fragment}` : ''})`;
}

/** A link from a page to a source file, as a path relative to the page. */
function sourceLink(reference: ReferenceProgram, fromPage: string, file: string): string {
  const docsDir = `${reference.packageDir}/docs/reference`;
  const relativeToRoot = relative(reference.packageDir, file);
  const path = relative(dirname(`${docsDir}/${fromPage}`), file);

  return `[${relativeToRoot}](${path})`;
}

function cell(text: string): string {
  return text
    .replace(/\s*\n\s*/g, ' ')
    .replace(/\|/g, '\\|')
    .trim();
}

function code(text: string): string {
  return `\`${text.replace(/`/g, '\\`')}\``;
}

function table(headers: string[], rows: string[][]): string {
  const lines = [`| ${headers.join(' | ')} |`, `| ${headers.map(() => '---').join(' | ')} |`];

  for (const row of rows) lines.push(`| ${row.map(cell).join(' | ')} |`);

  return lines.join('\n');
}

function fence(language: string, body: string): string {
  return `\`\`\`${language}\n${body.trimEnd()}\n\`\`\``;
}

/**
 * Dedent an `@example` body and keep it a fenced block; one that is already fenced is used as written. The tag's first
 * line comes without its indent, so the indent is measured on the lines after it.
 */
function exampleBlock(text: string): string {
  const [first = '', ...rest] = text.split('\n');
  const indented = rest.filter((line) => line.trim());
  const indent = indented.length ? Math.min(...indented.map((line) => line.length - line.trimStart().length)) : 0;
  const body = [first.trim(), ...rest.map((line) => line.slice(indent))].join('\n').trim();
  // The formatter leaves `;` after a closing fence inside JSDoc; it would keep the block open in Markdown.
  if (body.startsWith('```')) return body.replace(/```;\s*$/, '```');

  return fence('ts', body);
}

/** Headings inside a JSDoc body, demoted so they nest under the symbol's `##` heading. */
function demoteHeadings(text: string): string {
  let inFence = false;

  return text
    .split('\n')
    .map((line) => {
      if (/^\s*```/.test(line)) inFence = !inFence;

      if (inFence) return line;

      return line.replace(/^(#{1,4})(\s)/, (_match, hashes: string, space: string) => `${hashes}##${space}`);
    })
    .join('\n');
}

function docBody(doc: DocBlock): string {
  const parts: string[] = [doc.text ? demoteHeadings(doc.text) : NO_DESCRIPTION];

  for (const tag of doc.tags) {
    if (tag.name === 'example') parts.push(exampleBlock(tag.text));
    else parts.push(`**@${tag.name}**${tag.text ? ` ${tag.text}` : ''}`);
  }

  return parts.join('\n\n');
}

function docCell(doc: DocBlock): string {
  return doc.text || NO_DESCRIPTION;
}

/** A type (or default) for a table cell: inline when short, else a reference to a block rendered under the table. */
class LongCells {
  private readonly blocks: string[] = [];

  cell(key: string, what: string, text: string, language = 'ts'): string {
    if (text.length <= LONG_CELL) return code(text);

    this.blocks.push(`${code(key)} ${what}:\n\n${fence(language, text)}`);
    return `see ${what} below`;
  }

  render(): string {
    return this.blocks.join('\n\n');
  }
}

function section(parts: (string | undefined)[]): string {
  return parts.filter((part): part is string => !!part).join('\n\n');
}

// ── Behaviors ────────────────────────────────────────────────────────────────

function behaviorPage(info: BehaviorInfo): string | undefined {
  return info.entry?.page;
}

/** A link to a behavior's heading, or to its source when it has no page (a behavior built inline in a feature). */
function behaviorLink(reference: ReferenceProgram, fromPage: string, info: BehaviorInfo): string {
  const page = behaviorPage(info);
  if (page) return link(fromPage, page, info.name, anchor(info.name));

  return `${code(info.label)} (${sourceLink(reference, fromPage, info.file)})`;
}

function ownerCell(reference: ReferenceProgram, fromPage: string, row: SlotRow, pageFile: string): string {
  if (!row.owner) return '—';

  const name = row.owner.name ? code(row.owner.name) : 'inline';

  if (row.owner.file === pageFile) return name;

  const entry = reference.entries.find((candidate) => candidate.file === row.owner?.file);
  const target = entry?.page ? link(fromPage, entry.page, entry.key) : sourceLink(reference, fromPage, row.owner.file);

  return `${name} (${target})`;
}

function slotTable(
  reference: ReferenceProgram,
  fromPage: string,
  pageFile: string,
  rows: SlotRow[],
  declaredKeys: string[] | undefined
): string | undefined {
  if (rows.length === 0) return undefined;

  const long = new LongCells();
  const declaredColumn = declaredKeys !== undefined;
  const headers = ['Key', 'Access', ...(declaredColumn ? ['Declared'] : []), 'Type', 'Owner', 'Doc'];
  const body = rows.map((row) => [
    code(row.key),
    row.access,
    ...(declaredColumn ? [row.declared ? 'yes' : row.optional ? 'reads if present' : 'no'] : []),
    long.cell(row.key, 'type', row.type),
    ownerCell(reference, fromPage, row, pageFile),
    docCell(row.doc),
  ]);

  return section([table(headers, body), long.render()]);
}

function configTable(rows: ConfigRow[]): string | undefined {
  if (rows.length === 0) return undefined;

  const long = new LongCells();
  const body = rows.map((row) => [
    code(row.optional ? `${row.key}?` : row.key),
    long.cell(row.key, 'type', row.type),
    docCell(row.doc),
  ]);

  return section([table(['Key', 'Type', 'Doc'], body), long.render()]);
}

function behaviorSection(reference: ReferenceProgram, page: string, info: BehaviorInfo): string {
  const configNote =
    info.configOptional === undefined
      ? undefined
      : info.configOptional
        ? 'The setup declares `config?`: callers may omit it.'
        : 'The setup declares `config` as required.';
  const keysNote = [
    info.stateKeys === undefined ? '`stateKeys` are not derivable from the type or the initializer.' : undefined,
    info.contextKeys === undefined ? '`contextKeys` are not derivable from the type or the initializer.' : undefined,
  ].filter(Boolean);
  const config = configTable(info.config);
  const state = slotTable(reference, page, info.file, info.state, info.stateKeys);
  const context = slotTable(reference, page, info.file, info.context, info.contextKeys);

  return section([
    `## ${info.name}`,
    docBody(info.doc),
    `Source: ${sourceLink(reference, page, info.file)}`,
    keysNote.length ? keysNote.join(' ') : undefined,
    config || configNote ? '### Config' : undefined,
    config ? configNote : undefined,
    config ?? (configNote ? `${configNote} It has no keys.` : undefined),
    state ? '### State' : undefined,
    state,
    context ? '### Context' : undefined,
    context,
  ]);
}

/** The module's exports that are not rendered as their own sections: name, kind, first sentence, source. */
function otherExports(
  reference: ReferenceProgram,
  page: string,
  entry: EntryPoint,
  rendered: Set<string>
): string | undefined {
  const { checker } = reference;
  const rows: string[][] = [];

  for (const exported of moduleExports(reference, entry.file)) {
    if (rendered.has(exported.name)) continue;

    const symbol = resolveAlias(checker, exported);
    const file = declaringFile(symbol) ?? entry.file;
    const doc = docOf(checker, symbol);

    rows.push([
      code(exported.name),
      exportKind(symbol),
      firstSentence(doc) || NO_DESCRIPTION,
      sourceLink(reference, page, file),
    ]);
  }

  if (rows.length === 0) return undefined;

  rows.sort((a, b) => a[0]!.localeCompare(b[0]!));

  return section(['## Other exports', table(['Name', 'Kind', 'Description', 'Source'], rows)]);
}

function renderBehaviorPage(reference: ReferenceProgram, model: Model, entry: EntryPoint): string {
  const page = entry.page!;
  const behaviors = model.behaviors.filter((info) => info.entry === entry).sort((a, b) => a.name.localeCompare(b.name));

  return section([
    GENERATED_NOTICE,
    `# ${code(entry.specifier)}`,
    `Source: ${sourceLink(reference, page, entry.file)}`,
    ...behaviors.map((info) => behaviorSection(reference, page, info)),
    otherExports(reference, page, entry, new Set(behaviors.map((info) => info.name))),
  ]);
}

// ── Features and engines ─────────────────────────────────────────────────────

/** Behaviors among `behaviors` that read config key `key`, in composition order. */
function readersOf(behaviors: BehaviorInfo[], key: string): BehaviorInfo[] {
  return behaviors.filter((info) => info.config.some((row) => row.key === key));
}

/** The config field doc the first reader with one gives. */
function configDoc(readers: BehaviorInfo[], key: string): DocBlock | undefined {
  for (const reader of readers) {
    const row = reader.config.find((candidate) => candidate.key === key);
    if (row?.doc.text) return row.doc;
  }

  return undefined;
}

function slotOf(info: BehaviorInfo, slot: 'state' | 'context', key: string): SlotRow | undefined {
  return info[slot].find((row) => row.key === key);
}

/** The slot doc from the first behavior that writes the key, else the first that reads it. */
function slotDoc(behaviors: BehaviorInfo[], slot: 'state' | 'context', key: string): DocBlock | undefined {
  const rows = behaviors.map((info) => slotOf(info, slot, key)).filter((row): row is SlotRow => !!row);
  const documented = [
    ...rows.filter((row) => row.access === 'writes'),
    ...rows.filter((row) => row.access === 'reads'),
  ];

  return documented.find((row) => row.doc.text)?.doc;
}

function behaviorLinks(reference: ReferenceProgram, page: string, behaviors: BehaviorInfo[]): string {
  return behaviors.length ? behaviors.map((info) => behaviorLink(reference, page, info)).join(', ') : '—';
}

function slotFieldsTable(
  reference: ReferenceProgram,
  page: string,
  fields: TypeField[],
  behaviors: BehaviorInfo[],
  slot: 'state' | 'context'
): string | undefined {
  if (fields.length === 0) return undefined;

  const long = new LongCells();
  const rows = fields.map((field) => {
    const declaredBy = behaviors.filter((info) => slotOf(info, slot, field.key)?.declared);
    const doc = slotDoc(behaviors, slot, field.key);

    return [
      code(field.optional ? `${field.key}?` : field.key),
      long.cell(field.key, 'type', field.type),
      behaviorLinks(reference, page, declaredBy),
      doc ? docCell(doc) : NO_DESCRIPTION,
    ];
  });

  return section([table(['Key', 'Type', 'Declared by', 'Doc'], rows), long.render()]);
}

/**
 * The behaviors a feature's `defaultConfig` key is for: the feature's own readers in composition order, then the
 * behaviors the literal's `satisfies` type names (the declarations behind the key), alphabetical. A key no `satisfies`
 * clause covers falls back to every behavior that reads it.
 */
function defaultReaders(model: Model, feature: FeatureInfo, key: string): BehaviorInfo[] {
  const own = readersOf(feature.behaviors, key);
  const value = feature.defaults.find((candidate) => candidate.key === key);
  const declared = new Set(value?.readerDeclarations ?? []);
  const others = readersOf(model.behaviors, key)
    .filter((info) => !own.includes(info))
    .filter(
      (info) =>
        declared.size === 0 ||
        info.config.some((row) => row.key === key && row.declarations.some((declaration) => declared.has(declaration)))
    )
    .sort((a, b) => a.name.localeCompare(b.name));

  return [...own, ...others];
}

function featureConfigTable(
  reference: ReferenceProgram,
  model: Model,
  page: string,
  feature: FeatureInfo
): string | undefined {
  const keys = [...new Set([...feature.config.map((f) => f.key), ...feature.defaults.map((d) => d.key)])].sort();
  if (keys.length === 0) return undefined;

  const long = new LongCells();
  const rows = keys.map((key) => {
    const field = feature.config.find((candidate) => candidate.key === key);
    const value = feature.defaults.find((candidate) => candidate.key === key);
    const readers = defaultReaders(model, feature, key);
    const type = field?.type ?? value?.type ?? readers[0]?.config.find((row) => row.key === key)?.type;
    const doc = configDoc(readers, key);

    return [
      code(field ? (field.optional ? `${key}?` : key) : key),
      type ? long.cell(key, 'type', type) : '—',
      value ? long.cell(key, 'default', value.text) : '—',
      behaviorLinks(reference, page, readers),
      doc ? docCell(doc) : NO_DESCRIPTION,
    ];
  });

  return section([table(['Key', 'Type', 'Default', 'Read by', 'Doc'], rows), long.render()]);
}

function renderFeaturePage(reference: ReferenceProgram, model: Model, feature: FeatureInfo): string {
  const page = feature.entry.page!;
  // A behavior built inline in the feature's list is shown as written, since this page is where it is defined.
  const behaviors = feature.behaviors.length
    ? feature.behaviors
        .map((info, index) => `${index + 1}. ${info.exported ? behaviorLink(reference, page, info) : code(info.name)}`)
        .join('\n')
    : 'None.';
  const config = featureConfigTable(reference, model, page, feature);
  const state = slotFieldsTable(reference, page, feature.state, feature.behaviors, 'state');
  const context = slotFieldsTable(reference, page, feature.context, feature.behaviors, 'context');
  const composedBy = feature.composedBy.length
    ? feature.composedBy.map((engine) => `- ${link(page, engine.entry.page!, engine.entry.specifier)}`).join('\n')
    : 'None.';

  return section([
    GENERATED_NOTICE,
    `# ${code(feature.entry.specifier)}`,
    `Source: ${sourceLink(reference, page, feature.file)}`,
    `## ${feature.name}`,
    docBody(feature.doc),
    '### Behaviors',
    behaviors,
    config ? '### Config' : undefined,
    config,
    state ? '### State' : undefined,
    state,
    context ? '### Context' : undefined,
    context,
    '### Composed by',
    composedBy,
    otherExports(reference, page, feature.entry, new Set([feature.name])),
  ]);
}

function engineConfigTable(reference: ReferenceProgram, page: string, engine: EngineInfo): string | undefined {
  if (engine.config.length === 0) return undefined;

  const long = new LongCells();
  const rows = engine.config.map((field) => {
    // A later feature's `defaultConfig` key replaces an earlier one's.
    const supplier = [...engine.features]
      .reverse()
      .find((feature) => feature.defaults.some((value) => value.key === field.key));
    const value = supplier?.defaults.find((candidate) => candidate.key === field.key);
    const readers = readersOf(engine.behaviors, field.key);
    const doc = configDoc(readers, field.key);

    return [
      code(field.optional ? `${field.key}?` : field.key),
      long.cell(field.key, 'type', field.type),
      value ? long.cell(field.key, 'default', value.text) : '—',
      supplier ? link(page, supplier.entry.page!, supplier.name) : '—',
      behaviorLinks(reference, page, readers),
      doc ? docCell(doc) : NO_DESCRIPTION,
    ];
  });

  return section([table(['Key', 'Type', 'Default', 'Default from', 'Read by', 'Doc'], rows), long.render()]);
}

function renderEnginePage(reference: ReferenceProgram, engine: EngineInfo): string {
  const page = engine.entry.page!;
  const features = engine.features
    .map((feature, index) => `${index + 1}. ${link(page, feature.entry.page!, feature.name)}`)
    .join('\n');
  const behaviors = engine.behaviors
    .map((info, index) => `${index + 1}. ${behaviorLink(reference, page, info)}`)
    .join('\n');
  const config = engineConfigTable(reference, page, engine);
  const state = slotFieldsTable(reference, page, engine.state, engine.behaviors, 'state');
  const context = slotFieldsTable(reference, page, engine.context, engine.behaviors, 'context');

  return section([
    GENERATED_NOTICE,
    `# ${code(engine.entry.specifier)}`,
    `Source: ${sourceLink(reference, page, engine.file)}`,
    '## createEngine',
    docBody(engine.doc),
    '### Features',
    features,
    '### Behaviors',
    behaviors,
    config ? '### Config' : undefined,
    config,
    state ? '### State' : undefined,
    state,
    context ? '### Context' : undefined,
    context,
    otherExports(reference, page, engine.entry, new Set(['createEngine'])),
  ]);
}

// ── Core ─────────────────────────────────────────────────────────────────────

interface CoreModule {
  /** The module name, e.g. `define-behavior`. */
  name: string;
  page: string;
  file: string;
  /** Export names the root entry re-exports from the module, alphabetical. */
  exports: string[];
}

/** The root entry's re-exports from `src/core/composition/`, grouped by module. */
function coreModules(reference: ReferenceProgram): CoreModule[] {
  const root = reference.entries.find((entry) => entry.key === 'index');
  if (!root) throw new Error('No `index` entry');

  const sourceFile = reference.program.getSourceFile(root.file);
  if (!sourceFile) throw new Error(`Not in the program: ${root.file}`);

  const modules = new Map<string, CoreModule>();

  for (const statement of sourceFile.statements) {
    if (!ts.isExportDeclaration(statement) || !statement.moduleSpecifier) continue;

    if (!ts.isStringLiteralLike(statement.moduleSpecifier)) continue;

    const specifier = statement.moduleSpecifier.text;
    if (!specifier.startsWith(CORE_MODULE_PREFIX)) continue;

    const name = specifier.slice(CORE_MODULE_PREFIX.length);
    const module = modules.get(name) ?? {
      name,
      page: `core/${name}.md`,
      file: `${dirname(root.file)}/core/composition/${name}.ts`,
      exports: [],
    };

    modules.set(name, module);

    const clause = statement.exportClause;

    if (clause && ts.isNamedExports(clause)) {
      for (const element of clause.elements) module.exports.push(element.name.text);
    }
  }

  for (const module of modules.values()) module.exports.sort();

  return [...modules.values()].sort((a, b) => a.name.localeCompare(b.name));
}

function renderCorePage(reference: ReferenceProgram, module: CoreModule): string {
  const { checker } = reference;
  const exports = new Map(moduleExports(reference, module.file).map((symbol) => [symbol.name, symbol]));
  const sections = module.exports.map((name) => {
    const symbol = exports.get(name);
    if (!symbol) throw new Error(`${module.file} does not export \`${name}\``);

    const resolved = resolveAlias(checker, symbol);
    const signature = declarationSignature(resolved);

    return section([
      `## ${name}`,
      docBody(docOf(checker, resolved)),
      signature ? fence('ts', signature) : undefined,
      `Source: ${sourceLink(reference, module.page, declaringFile(resolved) ?? module.file)}`,
    ]);
  });

  return section([
    GENERATED_NOTICE,
    `# ${code(reference.packageName)}: ${module.name}`,
    `Exports of ${code(reference.packageName)} declared in ${sourceLink(reference, module.page, module.file)}.`,
    ...sections,
  ]);
}

// ── README ───────────────────────────────────────────────────────────────────

function mermaid(model: Model): string {
  const id = (prefix: string, name: string) => `${prefix}_${name.replace(/[^\w]/g, '_')}`;
  const lines = ['graph LR'];

  for (const engine of model.engines) {
    lines.push(`  ${id('engine', engine.name)}["${engine.entry.specifier}"]`);
  }

  for (const feature of model.features) {
    lines.push(`  ${id('feature', feature.entry.name)}["${feature.name}"]`);
  }

  for (const engine of model.engines) {
    for (const feature of engine.features) {
      lines.push(`  ${id('engine', engine.name)} --> ${id('feature', feature.entry.name)}`);
    }
  }

  return fence('mermaid', lines.join('\n'));
}

function renderReadme(reference: ReferenceProgram, model: Model, core: CoreModule[]): string {
  const { checker } = reference;
  const page = 'README.md';
  const uncovered = reference.entries
    .filter((entry) => !entry.layer && entry.key !== 'index')
    .map((entry) => code(entry.specifier));

  const coreRows = core.flatMap((module) => {
    const exports = new Map(moduleExports(reference, module.file).map((symbol) => [symbol.name, symbol]));

    return module.exports.map((name) => [
      code(name),
      link(page, module.page, module.name, anchor(name)),
      firstSentence(docOf(checker, resolveAlias(checker, exports.get(name)!))) || NO_DESCRIPTION,
    ]);
  });
  const engineRows = model.engines.map((engine) => [
    code(engine.entry.specifier),
    link(page, engine.entry.page!, engine.name),
    firstSentence(engine.doc) || NO_DESCRIPTION,
  ]);
  const featureRows = model.features.map((feature) => [
    code(feature.name),
    link(page, feature.entry.page!, feature.entry.name),
    firstSentence(feature.doc) || NO_DESCRIPTION,
  ]);
  const behaviorRows = (layer: 'behavior' | 'behavior-dom') =>
    model.behaviors
      .filter((info) => info.entry?.layer === layer)
      .sort((a, b) => a.name.localeCompare(b.name))
      .map((info) => [
        code(info.name),
        link(page, info.entry!.page!, info.entry!.key, anchor(info.name)),
        firstSentence(info.doc) || NO_DESCRIPTION,
      ]);
  const headers = ['Symbol', 'Page', 'Description'];

  return section([
    GENERATED_NOTICE,
    `# ${code(reference.packageName)} API reference`,
    `Generated from the TypeScript sources and their JSDoc by \`scripts/build-reference.ts\`. It covers the composition factories the root entry exports from \`src/core/composition/\`, the playback engines (\`${reference.packageName}/hls/*\`), their features (\`${reference.packageName}/hls/features/*\`), and the behaviors (\`${reference.packageName}/behaviors/*\`). It does not cover the root entry's other exports, nor these entry points: ${uncovered.join(', ')}.`,
    'Regenerate with `pnpm -F @videojs/spf docs:reference`; `pnpm -F @videojs/spf docs:reference:check` fails when the committed output is stale. A symbol without JSDoc reads "No description."',
    'On feature and engine pages, a config key\'s doc is the config field JSDoc of the first behavior listed under "Read by" that has one, and a state or context key\'s doc is the field JSDoc from the first behavior that writes the key, else the first that reads it.',
    '## Engines and features',
    mermaid(model),
    '## Core',
    table(headers, coreRows),
    '## Engines',
    table(headers, engineRows),
    '## Features',
    table(headers, featureRows),
    '## Behaviors',
    table(headers, behaviorRows('behavior')),
    '## Behaviors (DOM)',
    table(headers, behaviorRows('behavior-dom')),
  ]);
}

// ── Entry ────────────────────────────────────────────────────────────────────

export function renderPages(reference: ReferenceProgram, model: Model): Pages {
  const pages: Pages = new Map();
  const core = coreModules(reference);

  pages.set('README.md', renderReadme(reference, model, core));

  for (const module of core) pages.set(module.page, renderCorePage(reference, module));

  for (const entry of reference.entries) {
    if (entry.layer === 'behavior' || entry.layer === 'behavior-dom') {
      pages.set(entry.page!, renderBehaviorPage(reference, model, entry));
    }
  }

  for (const feature of model.features) pages.set(feature.entry.page!, renderFeaturePage(reference, model, feature));

  for (const engine of model.engines) pages.set(engine.entry.page!, renderEnginePage(reference, engine));

  for (const [path, content] of pages) pages.set(path, `${content.replace(/\r\n/g, '\n').trimEnd()}\n`);

  return pages;
}
