/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */

import type { FlatTranslations, Translations } from './params';
import { findLocaleKeys, getLocaleKey, hasRegisteredLocale } from './registry';
import { flattenTranslations } from './utils';

const loaders = {
  ar: () => import('./locales/ar'),
  az: () => import('./locales/az'),
  bs: () => import('./locales/bs'),
  bg: () => import('./locales/bg'),
  bn: () => import('./locales/bn'),
  ca: () => import('./locales/ca'),
  cs: () => import('./locales/cs'),
  cy: () => import('./locales/cy'),
  da: () => import('./locales/da'),
  de: () => import('./locales/de'),
  el: () => import('./locales/el'),
  es: () => import('./locales/es'),
  et: () => import('./locales/et'),
  eu: () => import('./locales/eu'),
  fa: () => import('./locales/fa'),
  fi: () => import('./locales/fi'),
  fr: () => import('./locales/fr'),
  gd: () => import('./locales/gd'),
  gl: () => import('./locales/gl'),
  he: () => import('./locales/he'),
  hi: () => import('./locales/hi'),
  hr: () => import('./locales/hr'),
  hu: () => import('./locales/hu'),
  id: () => import('./locales/id'),
  it: () => import('./locales/it'),
  ja: () => import('./locales/ja'),
  ko: () => import('./locales/ko'),
  lt: () => import('./locales/lt'),
  lv: () => import('./locales/lv'),
  mr: () => import('./locales/mr'),
  nb: () => import('./locales/nb'),
  nl: () => import('./locales/nl'),
  nn: () => import('./locales/nn'),
  ne: () => import('./locales/ne'),
  oc: () => import('./locales/oc'),
  pl: () => import('./locales/pl'),
  'pt-br': () => import('./locales/pt-BR'),
  'pt-pt': () => import('./locales/pt-PT'),
  ro: () => import('./locales/ro'),
  ru: () => import('./locales/ru'),
  sk: () => import('./locales/sk'),
  sl: () => import('./locales/sl'),
  sr: () => import('./locales/sr'),
  sv: () => import('./locales/sv'),
  te: () => import('./locales/te'),
  th: () => import('./locales/th'),
  tr: () => import('./locales/tr'),
  uk: () => import('./locales/uk'),
  vi: () => import('./locales/vi'),
  'zh-cn': () => import('./locales/zh-CN'),
  'zh-tw': () => import('./locales/zh-TW'),
  pt: () => import('./locales/pt'),
  zh: () => import('./locales/zh'),
} as const satisfies Record<string, () => Promise<{ default: Translations }>>;

/**
 * Lazy-import the built-in locale pack for a tag, or its closest fallback in the {@link findLocaleKeys} chain. Resolves
 * to `undefined` when that chain reaches a registered locale first or no built-in pack matches.
 *
 * @param tag - BCP 47 tag to load, such as `fr-CA`.
 * @public
 */
export async function loadLocale(tag: string): Promise<Partial<FlatTranslations> | undefined> {
  if (hasRegisteredLocale(tag)) return undefined;
  for (const chainTag of findLocaleKeys(tag)) {
    if (hasRegisteredLocale(chainTag)) return undefined;
    const load = loaders[getLocaleKey(chainTag) as keyof typeof loaders];
    if (load) return flattenTranslations((await load()).default);
  }
  return undefined;
}
