/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */

import type { Translations } from '../params';
import ar from './ar';
import az from './az';
import bg from './bg';
import bn from './bn';
import bs from './bs';
import ca from './ca';
import cs from './cs';
import cy from './cy';
import da from './da';
import de from './de';
import el from './el';
import en from './en';
import es from './es';
import et from './et';
import eu from './eu';
import fa from './fa';
import fi from './fi';
import fr from './fr';
import gd from './gd';
import gl from './gl';
import he from './he';
import hi from './hi';
import hr from './hr';
import hu from './hu';
import id from './id';
import it from './it';
import ja from './ja';
import ko from './ko';
import lt from './lt';
import lv from './lv';
import mr from './mr';
import nb from './nb';
import ne from './ne';
import nl from './nl';
import nn from './nn';
import oc from './oc';
import pl from './pl';
import pt from './pt';
import pt_BR from './pt-BR';
import pt_PT from './pt-PT';
import ro from './ro';
import ru from './ru';
import sk from './sk';
import sl from './sl';
import sr from './sr';
import sv from './sv';
import te from './te';
import th from './th';
import tr from './tr';
import uk from './uk';
import vi from './vi';
import zh from './zh';
import zh_CN from './zh-CN';
import zh_TW from './zh-TW';

/**
 * Every built-in locale pack keyed by BCP 47 tag.
 *
 * @internal
 */
export const all = {
  en,
  ar,
  az,
  bs,
  bg,
  bn,
  ca,
  cs,
  cy,
  da,
  de,
  el,
  es,
  et,
  eu,
  fa,
  fi,
  fr,
  gd,
  gl,
  he,
  hi,
  hr,
  hu,
  id,
  it,
  ja,
  ko,
  lt,
  lv,
  mr,
  nb,
  nl,
  nn,
  ne,
  oc,
  pl,
  'pt-BR': pt_BR,
  'pt-PT': pt_PT,
  ro,
  ru,
  sk,
  sl,
  sr,
  sv,
  te,
  th,
  tr,
  uk,
  vi,
  'zh-CN': zh_CN,
  'zh-TW': zh_TW,
  pt,
  zh,
} as const satisfies Record<string, Partial<Translations>>;

/** @internal */
export type LocaleTag = keyof typeof all;

/**
 * BCP 47 tags for every pack in {@link all}.
 *
 * @internal
 */
export const localeTags = Object.keys(all) as LocaleTag[];
