name: PR title check

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  pr-title-lint:
    name: Should follow conventional commit spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: read node version from .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        shell: bash
        id: nvm
      - uses: actions/setup-node@v4
        with:
          node-version: '${{steps.nvm.outputs.NVMRC}}'
      - run: npm i @actions/core @actions/github
      - run: node .github/actions/pr-titles.mjs
